// GENERATED by tools/content-pipeline/compute-popular-taxonomy.ts — DO NOT EDIT BY HAND.
// Re-run after adding/removing books:
//   pnpm --filter @cloudquran/content-pipeline compute-popular-taxonomy
// The most-common categories/topics across the full catalogue, ranked by
// linked-book count (most books first). Read by the Discover home chip rows.

/** Category slugs, most books first. */
export const POPULAR_CATEGORIES: string[] = [
  'personal-development',
  'business',
  'psychology',
  'leadership',
  'politics-society',
  'history',
  'philosophy',
  'science',
  'technology',
  'biography-memoir',
  'economics-finance',
  'career',
  'communication',
  'health-wellness',
  'relationships',
  'marketing-sales',
];

/** Topic names, most books first. */
export const POPULAR_TOPICS: string[] = [
  'Psychology',
  'Business Strategy',
  'Leadership',
  'Communication Skills',
  'Innovation',
  'Self-Improvement',
  'Entrepreneurship',
  'The Brain',
  'Neuroscience',
  'Self-Awareness',
  'Career Development',
  'Motivation',
  'Startups',
  'Management',
  'Success Mindset',
  'Habits',
];
