/**
 * Story 36.5 — the SPANISH taxonomy labels: category display names, their short card variants, and
 * all 240 topic names. Mirrors `taxonomy-fr.ts` exactly in shape; see that file's header for the
 * two rules that matter, restated here because they are the two ways this file gets broken:
 *
 * ⚠️ THESE ARE LABELS, NOT QUERY KEYS. `categories.slug` and `topics.name` are what the `where`
 * clauses filter on (`{ 'categories.slug': … }`, `{ 'topics.name': … }`) and they stay English
 * forever. Only what a user READS changes. Translating a KEY here renders the chip and returns
 * nothing from the filter — a silent failure, so the keys below are byte-identical to the French
 * file's.
 *
 * ⚠️ AND THESE ARE NOT `t()` COPY, DELIBERATELY. `scripts/lint-i18n.mjs` roots its scan at
 * `apps/expo/src` alone, so this file is outside the gate by construction — the intended outcome,
 * not an oversight. Do NOT move these maps under `apps/expo/src`.
 *
 * Vocabulary follows the app's own Spanish, not what reads best in isolation:
 * `tools/content-pipeline/translate-ui-bundle.ts`'s hand-override register is the authority for
 * every term 36.4 settled (Apple's Spanish — "ajustes", "Toca", "Puntos clave").
 */

/** Canonical category slug → Spanish display name. One entry per canonical slug (35). */
export const CATEGORY_DISPLAY_NAMES_ES: Record<string, string> = {
  'art-design': 'Arte y diseño',
  'biography-memoir': 'Biografías y memorias',
  business: 'Negocios',
  career: 'Carrera profesional',
  'children-ya': 'Infantil y juvenil',
  'comics-graphic': 'Cómics y novela gráfica',
  communication: 'Comunicación',
  'cooking-food': 'Cocina y gastronomía',
  'economics-finance': 'Economía y finanzas',
  education: 'Educación',
  'fiction-literary': 'Ficción literaria',
  'fiction-mystery': 'Misterio y suspense',
  'fiction-romance': 'Romántica',
  'fiction-scifi-fantasy': 'Ciencia ficción y fantasía',
  'fiction-historical': 'Novela histórica',
  'health-wellness': 'Salud y bienestar',
  history: 'Historia',
  'home-lifestyle': 'Hogar y estilo de vida',
  humor: 'Humor',
  leadership: 'Liderazgo',
  'marketing-sales': 'Marketing y ventas',
  mindfulness: 'Atención plena',
  'nature-environment': 'Naturaleza y medio ambiente',
  'parenting-family': 'Crianza y familia',
  'personal-development': 'Desarrollo personal',
  philosophy: 'Filosofía',
  'politics-society': 'Política y sociedad',
  psychology: 'Psicología',
  relationships: 'Relaciones',
  religion: 'Religión',
  science: 'Ciencia',
  'sports-fitness': 'Deporte y fitness',
  technology: 'Tecnología',
  travel: 'Viajes y aventura',
  'true-crime': 'Crimen real',
};

/**
 * Canonical category slug → SHORT Spanish label for the icon-on-top cards.
 *
 * ⚠️ THIS IS THE MAP USERS ACTUALLY READ on Discover's quick-filter row and book detail's
 * category cards (`getCategoryShortName`; the full name is only their `accessibilityLabel`) — so
 * a language needs its OWN short entries, not a fallback to its (longer) full name. Spanish runs
 * long for the same reason French does: "Naturaleza y medio ambiente" and "Ciencia ficción y
 * fantasía" both grow well past the narrow card.
 *
 * Only long names need an entry; anything absent falls back to the full Spanish display name.
 *
 * ⚠️ **The budget is ~12 glyphs, MEASURED — not guessed** (36.5 smoke, iPhone 17 Pro, 88pt card).
 * Confirmed fitting: `Tecnología` · `Psicología` · `Biografías` · `Desarrollo` · `Literaria`.
 * Confirmed CLIPPING on the first pass, and the reason two entries below exist at all:
 * `Atención plena` rendered `Atención ple…` and `Ciencia ficción` rendered `Ciencia ficci…`.
 * A character count is the wrong instrument here (`Personal Dev` is 12 and fits) — if a label goes
 * past ~12, put it on a card and look before trusting it.
 */
export const CATEGORY_SHORT_NAMES_ES: Record<string, string> = {
  'biography-memoir': 'Biografías',
  career: 'Carrera',
  'children-ya': 'Infantil',
  'comics-graphic': 'Cómics',
  'cooking-food': 'Cocina',
  'economics-finance': 'Economía',
  'fiction-historical': 'Histórica',
  'fiction-literary': 'Literaria',
  'fiction-mystery': 'Misterio',
  // Keeps the SCI-FI half, not the fantasy half: the card's icon is 🚀, so `Fantasía` — which fits
  // just as well — would contradict the picture sitting above it. `fr` makes the same call (`SF`).
  'fiction-scifi-fantasy': 'C. ficción',
  'health-wellness': 'Salud',
  'home-lifestyle': 'Hogar',
  'marketing-sales': 'Marketing',
  // The loanword, not a shortening of `Atención plena` — Spanish publishing shelves this category
  // under `Mindfulness`, and it is the only form short enough to survive the card.
  mindfulness: 'Mindfulness',
  'nature-environment': 'Naturaleza',
  'parenting-family': 'Crianza',
  'personal-development': 'Desarrollo',
  'politics-society': 'Política',
  'sports-fitness': 'Deporte',
  travel: 'Viajes',
};

/**
 * Topic NAME (the English query key) → Spanish display name. All 240 live topics.
 *
 * Keyed by the exact `topics.name` value, because that string IS the query key every filter
 * passes to `where: { 'topics.name': … }`. A topic with no entry falls back to its English name,
 * so an ingest that mints a new topic degrades to one English chip rather than a blank one.
 */
export const TOPIC_DISPLAY_NAMES_ES: Record<string, string> = {
  Addiction: 'Adicción',
  Adolescence: 'Adolescencia',
  Adventure: 'Aventura',
  Advertising: 'Publicidad',
  Aging: 'Envejecimiento',
  'American History': 'Historia de Estados Unidos',
  'Ancient History': 'Historia antigua',
  Anxiety: 'Ansiedad',
  Architecture: 'Arquitectura',
  Art: 'Arte',
  'Art History': 'Historia del arte',
  'Artificial Intelligence': 'Inteligencia artificial',
  'Artists & Musicians': 'Artistas y músicos',
  'Asian History': 'Historia de Asia',
  Astronomy: 'Astronomía',
  Atheism: 'Ateísmo',
  Athletes: 'Deportistas',
  Attachment: 'Apego',
  'Behavioral Economics': 'Economía conductual',
  'Behavioral Psychology': 'Psicología conductual',
  Biography: 'Biografía',
  Biology: 'Biología',
  Biotechnology: 'Biotecnología',
  Blockchain: 'Blockchain',
  'Body Language': 'Lenguaje corporal',
  Branding: 'Identidad de marca',
  Buddhism: 'Budismo',
  Burnout: 'Burnout',
  'Business Ethics': 'Ética empresarial',
  'Business Leaders': 'Líderes empresariales',
  'Business Models': 'Modelos de negocio',
  'Business Strategy': 'Estrategia empresarial',
  Capitalism: 'Capitalismo',
  'Career Change': 'Cambio de carrera',
  'Career Development': 'Desarrollo profesional',
  Charisma: 'Carisma',
  Chemistry: 'Química',
  Childhood: 'Infancia',
  Christianity: 'Cristianismo',
  'Civil War': 'Guerra de Secesión',
  'Climate Change': 'Cambio climático',
  'Coaching & Mentoring': 'Coaching y mentoría',
  'Cognitive Biases': 'Sesgos cognitivos',
  'Cognitive Psychology': 'Psicología cognitiva',
  'Cold War': 'Guerra Fría',
  Colonialism: 'Colonialismo',
  'Coming of Age': 'Novela de aprendizaje',
  'Communication Skills': 'Habilidades de comunicación',
  Compassion: 'Compasión',
  Confidence: 'Confianza en uno mismo',
  Consciousness: 'Conciencia',
  Conservation: 'Conservación de la naturaleza',
  Copywriting: 'Redacción publicitaria',
  'Corporate Culture': 'Cultura corporativa',
  Cosmology: 'Cosmología',
  Creativity: 'Creatividad',
  'Critical Thinking': 'Pensamiento crítico',
  Cryptocurrency: 'Criptomonedas',
  Culture: 'Cultura',
  'Customer Experience': 'Experiencia del cliente',
  Cybersecurity: 'Ciberseguridad',
  'Data Science': 'Ciencia de datos',
  Dating: 'Citas amorosas',
  'Death & Dying': 'Muerte y final de vida',
  'Decision Making': 'Toma de decisiones',
  'Deep Work': 'Trabajo profundo',
  Democracy: 'Democracia',
  Depression: 'Depresión',
  Design: 'Diseño',
  Diet: 'Alimentación',
  'Difficult Conversations': 'Conversaciones difíciles',
  'Digital Marketing': 'Marketing digital',
  'Digital Transformation': 'Transformación digital',
  Discipline: 'Disciplina',
  'Disease Prevention': 'Prevención de enfermedades',
  Disruption: 'Disrupción',
  Dystopia: 'Distopía',
  'Eastern Philosophy': 'Filosofía oriental',
  Ecology: 'Ecología',
  Economics: 'Economía',
  'Emotional Intelligence': 'Inteligencia emocional',
  Emotions: 'Emociones',
  Entrepreneurship: 'Emprendimiento',
  Environment: 'Medio ambiente',
  Ethics: 'Ética',
  'European History': 'Historia de Europa',
  Evolution: 'Evolución',
  Exercise: 'Ejercicio físico',
  Existentialism: 'Existencialismo',
  Faith: 'Fe',
  'Family Dynamics': 'Dinámicas familiares',
  'Family Saga': 'Saga familiar',
  Fasting: 'Ayuno',
  Fatherhood: 'Paternidad',
  Feminism: 'Feminismo',
  Film: 'Cine',
  'Financial Independence': 'Independencia financiera',
  Fitness: 'Fitness',
  Focus: 'Concentración',
  'Free Will': 'Libre albedrío',
  Freelancing: 'Trabajo freelance',
  Friendship: 'Amistad',
  Genetics: 'Genética',
  Geopolitics: 'Geopolítica',
  Globalization: 'Globalización',
  'Goal Setting': 'Fijación de objetivos',
  Government: 'Gobierno',
  Gratitude: 'Gratitud',
  Grief: 'Duelo',
  'Growth Hacking': 'Growth hacking',
  'Gut Health': 'Salud intestinal',
  Habits: 'Hábitos',
  Happiness: 'Felicidad',
  Health: 'Salud',
  Hinduism: 'Hinduismo',
  'Hiring & Recruiting': 'Selección de personal',
  'Historical Figures': 'Figuras históricas',
  'Human Rights': 'Derechos humanos',
  Identity: 'Identidad',
  Immigration: 'Inmigración',
  Inequality: 'Desigualdad',
  Influence: 'Influencia',
  'Inner Peace': 'Paz interior',
  Innovation: 'Innovación',
  'International Relations': 'Relaciones internacionales',
  Investing: 'Inversión',
  Islam: 'Islam',
  'Job Searching': 'Búsqueda de empleo',
  Judaism: 'Judaísmo',
  Justice: 'Justicia',
  Leadership: 'Liderazgo',
  Listening: 'Escucha',
  Literature: 'Literatura',
  Logic: 'Lógica',
  Longevity: 'Longevidad',
  'Loss & Grief': 'Pérdida y duelo',
  Love: 'Amor',
  'Love & Romance': 'Amor y romance',
  'Machine Learning': 'Aprendizaje automático',
  Management: 'Gestión',
  'Marketing Strategy': 'Estrategia de marketing',
  Marriage: 'Matrimonio',
  Mathematics: 'Matemáticas',
  Meditation: 'Meditación',
  Memory: 'Memoria',
  'Mental Health': 'Salud mental',
  Midlife: 'Mediana edad',
  Mindfulness: 'Atención plena',
  'Modern History': 'Historia moderna',
  Morality: 'Moral',
  Motherhood: 'Maternidad',
  Motivation: 'Motivación',
  Music: 'Música',
  Nature: 'Naturaleza',
  Negotiation: 'Negociación',
  Networking: 'Red de contactos',
  Neuroscience: 'Neurociencia',
  'Nuclear Science': 'Ciencia nuclear',
  Nutrition: 'Nutrición',
  'Organizational Change': 'Cambio organizacional',
  Parenting: 'Crianza',
  'Peak Performance': 'Alto rendimiento',
  'Personal Finance': 'Finanzas personales',
  'Personal Transformation': 'Transformación personal',
  Persuasion: 'Persuasión',
  Philosophy: 'Filosofía',
  Photography: 'Fotografía',
  Physics: 'Física',
  'Political Figures': 'Figuras políticas',
  Politics: 'Política',
  'Pop Culture': 'Cultura pop',
  'Power & Corruption': 'Poder y corrupción',
  'Problem Solving': 'Resolución de problemas',
  Procrastination: 'Procrastinación',
  Productivity: 'Productividad',
  'Professional Skills': 'Habilidades profesionales',
  'Project Management': 'Gestión de proyectos',
  Psychology: 'Psicología',
  'Public Policy': 'Políticas públicas',
  'Public Speaking': 'Hablar en público',
  Purpose: 'Propósito',
  'Quantum Physics': 'Física cuántica',
  'Race & Ethnicity': 'Raza y etnia',
  'Real Estate Investing': 'Inversión inmobiliaria',
  Recovery: 'Recuperación',
  Redemption: 'Redención',
  Relationships: 'Relaciones',
  Religion: 'Religión',
  'Remote Work': 'Teletrabajo',
  Resilience: 'Resiliencia',
  'Retirement Planning': 'Planificación de la jubilación',
  Revolution: 'Revolución',
  'Risk Management': 'Gestión de riesgos',
  Robotics: 'Robótica',
  'Sales Techniques': 'Técnicas de venta',
  Science: 'Ciencia',
  Scientists: 'Científicos',
  'Self-Awareness': 'Autoconocimiento',
  'Self-Care': 'Autocuidado',
  'Self-Improvement': 'Superación personal',
  Sexuality: 'Sexualidad',
  Slavery: 'Esclavitud',
  Sleep: 'Sueño',
  'Small Business': 'Pequeña empresa',
  'Social Issues': 'Temas sociales',
  'Social Justice': 'Justicia social',
  'Social Psychology': 'Psicología social',
  'Social Skills': 'Habilidades sociales',
  Society: 'Sociedad',
  'Software Development': 'Desarrollo de software',
  'Space Exploration': 'Exploración espacial',
  Spirituality: 'Espiritualidad',
  Startups: 'Startups',
  'Stock Market': 'Bolsa de valores',
  Stoicism: 'Estoicismo',
  Storytelling: 'Narrativa',
  'Strategic Thinking': 'Pensamiento estratégico',
  'Stress Management': 'Gestión del estrés',
  'Success Mindset': 'Mentalidad de éxito',
  Survival: 'Supervivencia',
  Sustainability: 'Sostenibilidad',
  'Systems Thinking': 'Pensamiento sistémico',
  'Team Building': 'Cohesión de equipo',
  'The Brain': 'El cerebro',
  Therapy: 'Terapia',
  'Time Management': 'Gestión del tiempo',
  Trauma: 'Trauma',
  'Venture Capital': 'Capital riesgo',
  Virtue: 'Virtud',
  War: 'Guerra',
  'War & Military': 'Guerra y ejército',
  'Wealth Building': 'Creación de riqueza',
  'Weight Loss': 'Pérdida de peso',
  Wildlife: 'Fauna salvaje',
  'Work-Life Balance': 'Equilibrio vida-trabajo',
  'World History': 'Historia mundial',
  'Writers & Authors': 'Escritores y autores',
  'Writing Skills': 'Técnicas de escritura',
  'Young Adulthood': 'Juventud',
  Zen: 'Zen',
};
