/**
 * Story 24.14 (§ D6) — the FRENCH taxonomy labels: category display names, their short card
 * variants, and all 240 topic names.
 *
 * ⚠️ THESE ARE LABELS, NOT QUERY KEYS. `categories.slug` and `topics.name` are what the `where`
 * clauses filter on (`{ 'categories.slug': … }`, `{ 'topics.name': … }`) and they stay English
 * forever. Only what a user READS changes. A press handler or `testID` that carries the raw
 * English key beside a translated label is CORRECT, not a bug — `taxonomy.test.ts` pins it.
 *
 * ⚠️ AND THESE ARE NOT `t()` COPY, DELIBERATELY. `CATEGORY_DISPLAY_NAMES` was already a plain TS
 * map and the authority for category labels; routing 275 strings through i18next instead would add
 * 275 keys × N locales to the locale-parity harness for no gain, and would fork a category's label
 * between two authorities that can only ever disagree. `scripts/lint-i18n.mjs` roots its scan at
 * `apps/expo/src` alone, so this file is outside the gate by construction — which is the intended
 * outcome, not an oversight. Do NOT move these maps under `apps/expo/src`, where they WOULD be
 * scanned and would then have to be rerouted into the bundle to satisfy a gate that exists for
 * copy, not for a data table.
 *
 * Live at authoring time (2026-07-29): 33 category slugs and 240 topic names carry books. The
 * CATEGORY unit here is nonetheless the full **35 canonical slugs** — `CANONICAL_CATEGORY_SLUGS`
 * is the source of truth, and translating only the 33 with books today would leave two categories
 * permanently English the day a book lands in them.
 */

/** Canonical category slug → French display name. One entry per canonical slug (35). */
export const CATEGORY_DISPLAY_NAMES_FR: Record<string, string> = {
  'art-design': 'Art et design',
  'biography-memoir': 'Biographies et mémoires',
  business: 'Business',
  career: 'Carrière',
  'children-ya': 'Jeunesse et ados',
  'comics-graphic': 'BD et romans graphiques',
  communication: 'Communication',
  'cooking-food': 'Cuisine et gastronomie',
  'economics-finance': 'Économie et finance',
  education: 'Éducation',
  'fiction-literary': 'Fiction littéraire',
  'fiction-mystery': 'Polar et thriller',
  'fiction-romance': 'Romance',
  'fiction-scifi-fantasy': 'SF et fantasy',
  'fiction-historical': 'Roman historique',
  'health-wellness': 'Santé et bien-être',
  history: 'Histoire',
  'home-lifestyle': 'Maison et art de vivre',
  humor: 'Humour',
  leadership: 'Leadership',
  'marketing-sales': 'Marketing et vente',
  mindfulness: 'Pleine conscience',
  'nature-environment': 'Nature et environnement',
  'parenting-family': 'Parentalité et famille',
  'personal-development': 'Développement personnel',
  philosophy: 'Philosophie',
  'politics-society': 'Politique et société',
  psychology: 'Psychologie',
  relationships: 'Relations',
  religion: 'Religion',
  science: 'Science',
  'sports-fitness': 'Sport et fitness',
  technology: 'Technologie',
  travel: 'Voyage et aventure',
  'true-crime': 'True crime',
};

/**
 * Canonical category slug → SHORT French label for the icon-on-top cards.
 *
 * ⚠️ THIS IS THE MAP USERS ACTUALLY READ on Discover's quick-filter row and book detail's
 * category cards (`getCategoryShortName`; the full name is only their `accessibilityLabel`) — so
 * a language needs its OWN short entries, not a fallback to its (longer) full name. French runs
 * materially longer than English here: English needs exactly TWO overrides, French needs
 * eighteen, because "Personal Development" → "Développement personnel" and "Health & Wellness" →
 * "Santé et bien-être" both grow past the narrow card.
 *
 * Only long names need an entry; anything absent falls back to the full French display name.
 */
export const CATEGORY_SHORT_NAMES_FR: Record<string, string> = {
  'biography-memoir': 'Biographies',
  'children-ya': 'Jeunesse',
  'comics-graphic': 'BD',
  'cooking-food': 'Cuisine',
  'economics-finance': 'Économie',
  'fiction-historical': 'Historique',
  'fiction-literary': 'Littéraire',
  'fiction-mystery': 'Polar',
  'fiction-scifi-fantasy': 'SF',
  'health-wellness': 'Santé',
  'home-lifestyle': 'Maison',
  'marketing-sales': 'Marketing',
  'nature-environment': 'Nature',
  'parenting-family': 'Parentalité',
  // 37.1: `Développement` (13) rendered `Développem…` on the 88pt card — a SHORT entry that was
  // itself too long, which is why "has a short name" is not the same as "fits". Measured on the
  // same row: `Philosophie`, `Technologie` and `Biographies` (11) all fit, so the ceiling sits
  // just under 12 for this glyph mix.
  'personal-development': 'Dév. perso',
  'politics-society': 'Politique',
  'sports-fitness': 'Sport',
  travel: 'Voyage',
};

/**
 * Topic NAME (the English query key) → French display name. All 240 live topics.
 *
 * Keyed by the exact `topics.name` value, because that string IS the query key every filter
 * passes to `where: { 'topics.name': … }`. A topic with no entry falls back to its English name,
 * so an ingest that mints a new topic degrades to one English chip rather than a blank one.
 */
export const TOPIC_DISPLAY_NAMES_FR: Record<string, string> = {
  Addiction: 'Addiction',
  Adolescence: 'Adolescence',
  Adventure: 'Aventure',
  Advertising: 'Publicité',
  Aging: 'Vieillissement',
  'American History': 'Histoire américaine',
  'Ancient History': 'Histoire antique',
  Anxiety: 'Anxiété',
  Architecture: 'Architecture',
  Art: 'Art',
  'Art History': "Histoire de l'art",
  'Artificial Intelligence': 'Intelligence artificielle',
  'Artists & Musicians': 'Artistes et musiciens',
  'Asian History': "Histoire de l'Asie",
  Astronomy: 'Astronomie',
  Atheism: 'Athéisme',
  Athletes: 'Athlètes',
  Attachment: 'Attachement',
  'Behavioral Economics': 'Économie comportementale',
  'Behavioral Psychology': 'Psychologie comportementale',
  Biography: 'Biographie',
  Biology: 'Biologie',
  Biotechnology: 'Biotechnologie',
  Blockchain: 'Blockchain',
  'Body Language': 'Langage corporel',
  Branding: 'Image de marque',
  Buddhism: 'Bouddhisme',
  Burnout: 'Burn-out',
  'Business Ethics': 'Éthique des affaires',
  'Business Leaders': "Dirigeants d'entreprise",
  'Business Models': 'Modèles économiques',
  'Business Strategy': "Stratégie d'entreprise",
  Capitalism: 'Capitalisme',
  'Career Change': 'Reconversion professionnelle',
  'Career Development': 'Évolution de carrière',
  Charisma: 'Charisme',
  Chemistry: 'Chimie',
  Childhood: 'Enfance',
  Christianity: 'Christianisme',
  'Civil War': 'Guerre de Sécession',
  'Climate Change': 'Changement climatique',
  'Coaching & Mentoring': 'Coaching et mentorat',
  'Cognitive Biases': 'Biais cognitifs',
  'Cognitive Psychology': 'Psychologie cognitive',
  'Cold War': 'Guerre froide',
  Colonialism: 'Colonialisme',
  'Coming of Age': "Récit d'apprentissage",
  'Communication Skills': 'Compétences en communication',
  Compassion: 'Compassion',
  Confidence: 'Confiance en soi',
  Consciousness: 'Conscience',
  Conservation: 'Conservation de la nature',
  Copywriting: 'Rédaction publicitaire',
  'Corporate Culture': "Culture d'entreprise",
  Cosmology: 'Cosmologie',
  Creativity: 'Créativité',
  'Critical Thinking': 'Esprit critique',
  Cryptocurrency: 'Cryptomonnaies',
  Culture: 'Culture',
  'Customer Experience': 'Expérience client',
  Cybersecurity: 'Cybersécurité',
  'Data Science': 'Science des données',
  Dating: 'Rencontres amoureuses',
  'Death & Dying': 'Mort et fin de vie',
  'Decision Making': 'Prise de décision',
  'Deep Work': 'Travail en profondeur',
  Democracy: 'Démocratie',
  Depression: 'Dépression',
  Design: 'Design',
  Diet: 'Alimentation',
  'Difficult Conversations': 'Conversations difficiles',
  'Digital Marketing': 'Marketing digital',
  'Digital Transformation': 'Transformation numérique',
  Discipline: 'Discipline',
  'Disease Prevention': 'Prévention des maladies',
  Disruption: 'Disruption',
  Dystopia: 'Dystopie',
  'Eastern Philosophy': 'Philosophie orientale',
  Ecology: 'Écologie',
  Economics: 'Économie',
  'Emotional Intelligence': 'Intelligence émotionnelle',
  Emotions: 'Émotions',
  Entrepreneurship: 'Entrepreneuriat',
  Environment: 'Environnement',
  Ethics: 'Éthique',
  'European History': "Histoire de l'Europe",
  Evolution: 'Évolution',
  Exercise: 'Exercice physique',
  Existentialism: 'Existentialisme',
  Faith: 'Foi',
  'Family Dynamics': 'Dynamiques familiales',
  'Family Saga': 'Saga familiale',
  Fasting: 'Jeûne',
  Fatherhood: 'Paternité',
  Feminism: 'Féminisme',
  Film: 'Cinéma',
  'Financial Independence': 'Indépendance financière',
  Fitness: 'Fitness',
  Focus: 'Concentration',
  'Free Will': 'Libre arbitre',
  Freelancing: 'Freelance',
  Friendship: 'Amitié',
  Genetics: 'Génétique',
  Geopolitics: 'Géopolitique',
  Globalization: 'Mondialisation',
  'Goal Setting': "Fixation d'objectifs",
  Government: 'Gouvernement',
  Gratitude: 'Gratitude',
  Grief: 'Deuil',
  'Growth Hacking': 'Growth hacking',
  'Gut Health': 'Santé intestinale',
  Habits: 'Habitudes',
  Happiness: 'Bonheur',
  Health: 'Santé',
  Hinduism: 'Hindouisme',
  'Hiring & Recruiting': 'Recrutement',
  'Historical Figures': 'Figures historiques',
  'Human Rights': 'Droits humains',
  Identity: 'Identité',
  Immigration: 'Immigration',
  Inequality: 'Inégalités',
  Influence: 'Influence',
  'Inner Peace': 'Paix intérieure',
  Innovation: 'Innovation',
  'International Relations': 'Relations internationales',
  Investing: 'Investissement',
  Islam: 'Islam',
  'Job Searching': "Recherche d'emploi",
  Judaism: 'Judaïsme',
  Justice: 'Justice',
  Leadership: 'Leadership',
  Listening: 'Écoute',
  Literature: 'Littérature',
  Logic: 'Logique',
  Longevity: 'Longévité',
  'Loss & Grief': 'Perte et deuil',
  Love: 'Amour',
  'Love & Romance': 'Amour et romance',
  'Machine Learning': 'Apprentissage automatique',
  Management: 'Management',
  'Marketing Strategy': 'Stratégie marketing',
  Marriage: 'Mariage',
  Mathematics: 'Mathématiques',
  Meditation: 'Méditation',
  Memory: 'Mémoire',
  'Mental Health': 'Santé mentale',
  Midlife: 'Milieu de vie',
  Mindfulness: 'Pleine conscience',
  'Modern History': 'Histoire moderne',
  Morality: 'Morale',
  Motherhood: 'Maternité',
  Motivation: 'Motivation',
  Music: 'Musique',
  Nature: 'Nature',
  Negotiation: 'Négociation',
  Networking: 'Réseautage',
  Neuroscience: 'Neurosciences',
  'Nuclear Science': 'Sciences nucléaires',
  Nutrition: 'Nutrition',
  'Organizational Change': 'Changement organisationnel',
  Parenting: 'Parentalité',
  'Peak Performance': 'Performance optimale',
  'Personal Finance': 'Finances personnelles',
  'Personal Transformation': 'Transformation personnelle',
  Persuasion: 'Persuasion',
  Philosophy: 'Philosophie',
  Photography: 'Photographie',
  Physics: 'Physique',
  'Political Figures': 'Figures politiques',
  Politics: 'Politique',
  'Pop Culture': 'Culture pop',
  'Power & Corruption': 'Pouvoir et corruption',
  'Problem Solving': 'Résolution de problèmes',
  Procrastination: 'Procrastination',
  Productivity: 'Productivité',
  'Professional Skills': 'Compétences professionnelles',
  'Project Management': 'Gestion de projet',
  Psychology: 'Psychologie',
  'Public Policy': 'Politiques publiques',
  'Public Speaking': 'Prise de parole en public',
  Purpose: "Raison d'être",
  'Quantum Physics': 'Physique quantique',
  'Race & Ethnicity': 'Race et ethnicité',
  'Real Estate Investing': 'Investissement immobilier',
  Recovery: 'Rétablissement',
  Redemption: 'Rédemption',
  Relationships: 'Relations',
  Religion: 'Religion',
  'Remote Work': 'Télétravail',
  Resilience: 'Résilience',
  'Retirement Planning': 'Préparation à la retraite',
  Revolution: 'Révolution',
  'Risk Management': 'Gestion des risques',
  Robotics: 'Robotique',
  'Sales Techniques': 'Techniques de vente',
  Science: 'Science',
  Scientists: 'Scientifiques',
  'Self-Awareness': 'Connaissance de soi',
  'Self-Care': 'Prendre soin de soi',
  'Self-Improvement': 'Développement personnel',
  Sexuality: 'Sexualité',
  Slavery: 'Esclavage',
  Sleep: 'Sommeil',
  'Small Business': 'Petite entreprise',
  'Social Issues': 'Enjeux de société',
  'Social Justice': 'Justice sociale',
  'Social Psychology': 'Psychologie sociale',
  'Social Skills': 'Compétences sociales',
  Society: 'Société',
  'Software Development': 'Développement logiciel',
  'Space Exploration': 'Exploration spatiale',
  Spirituality: 'Spiritualité',
  Startups: 'Startups',
  'Stock Market': 'Marchés boursiers',
  Stoicism: 'Stoïcisme',
  Storytelling: 'Narration',
  'Strategic Thinking': 'Pensée stratégique',
  'Stress Management': 'Gestion du stress',
  'Success Mindset': "État d'esprit de réussite",
  Survival: 'Survie',
  Sustainability: 'Développement durable',
  'Systems Thinking': 'Pensée systémique',
  'Team Building': "Cohésion d'équipe",
  'The Brain': 'Le cerveau',
  Therapy: 'Thérapie',
  'Time Management': 'Gestion du temps',
  Trauma: 'Traumatisme',
  'Venture Capital': 'Capital-risque',
  Virtue: 'Vertu',
  War: 'Guerre',
  'War & Military': 'Guerre et armée',
  'Wealth Building': 'Constitution de patrimoine',
  'Weight Loss': 'Perte de poids',
  Wildlife: 'Faune sauvage',
  'Work-Life Balance': 'Équilibre vie pro / vie perso',
  'World History': 'Histoire mondiale',
  'Writers & Authors': 'Écrivains et auteurs',
  'Writing Skills': "Techniques d'écriture",
  'Young Adulthood': 'Jeune âge adulte',
  Zen: 'Zen',
};
