/**
 * mushafLayout — the one door to the bundled 604-page mushaf layout data (story 6-2).
 *
 * ── Why the monolith JSON, lazily ────────────────────────────────────────────────────────────
 *
 * The data is `@/data/mushaf-layouts.json` — 7.8 MB minified, keyed `"1".."604"`, regenerated by
 * `scripts/generate-mushaf-layout.ts` from two pinned upstreams. Per-page `require`s would need a
 * generated 604-entry map for the same bundle bytes, and SQLite would drag `lint:layers` rule 8
 * and the data pipeline into scope for a file that never changes at runtime. One `require`,
 * deferred until the first mushaf page is opened, is the pre-fork shape and the cheapest one.
 *
 * ⚠️ THE `require` IS INSIDE THE FUNCTION, NOT AT MODULE SCOPE, AND THAT PLACEMENT IS THE
 * FEATURE. At module scope the 7.8 MB parse runs at BOOT — this module is imported (via the
 * feature barrel) by the route tree, so every cold launch would pay it whether or not the reader
 * ever opens the mushaf. Inside the accessor, Metro still bundles the asset but the parse cost is
 * paid on the first `getPageLayout` call. The async signature over a sync body is deliberate for
 * the same reason `getSurahVerses` is async: storage can change later (per-page files, SQLite)
 * without touching a caller, and the page component already treats the read as awaitable.
 *
 * ⚠️ NOT THE SYNC CLIENT, AND NOT `quranDb.ts` — same reasoning as `useSurah`'s header: this data
 * has no server copy and is identical for every reader, so it must not be keyed by user id; and
 * it is JSON in the JS bundle, not a SQLite database, so rule 8's chokepoint does not apply.
 * The Quran-text integrity gate does NOT cover it (`pnpm verify` hashes `uthmani_text` only) —
 * what protects it is that nothing here, or anywhere, writes it.
 */

import type { MushafPageLayout } from 'quran-data';
import { TOTAL_PAGES } from 'quran-data';

/** Parsed monolith, cached after the first read. */
let layouts: Record<string, MushafPageLayout> | null = null;

/**
 * The layout for one page (1–604).
 *
 * ⚠️ THROWS A TYPED, NAMED ERROR for a page the bundle does not hold — a missing page is a build
 * defect (the generator hard-validates 604 pages), and the page component turns the rejection
 * into an error surface with a retry rather than a blank screen.
 */
export async function getPageLayout(page: number): Promise<MushafPageLayout> {
  if (!layouts) {
    layouts = require('@/data/mushaf-layouts.json') as Record<string, MushafPageLayout>;
  }
  const layout = layouts[String(page)];
  if (!layout) {
    throw new Error(`No mushaf layout for page ${page} (expected 1-${TOTAL_PAGES})`);
  }
  return layout;
}
