/**
 * THE ADVERSARIAL AUTHORIZATION SUITE — the thing the layer this replaces never had.
 *
 * ⚠️ WHY IT IS AN INTEGRATION TEST AND NOT A UNIT TEST. The previous data layer's ownership rule
 * bound `isOwner` to `auth.id == data.creator`, and `creator` was in neither the schema nor any
 * write — so every create was denied for the life of the project and nobody noticed, because
 * nothing ever executed the rule against two identities. A rule nothing exercises is not a rule.
 * So this boots the REAL worker under `wrangler dev` against a REAL local D1, mints two distinct
 * identities through the `getUserId` seam, and asserts that every cross-user READ *and* every
 * cross-user WRITE is refused. A denial covering only reads is the exact bug this story exists
 * to prevent.
 *
 * ⚠️ STORY 5-5 KEPT THE PROMISE THE 5-4 HEADER MADE. Every isolation, LWW, union-merge and
 * ceiling assertion below is unchanged. What moved is only how an identity is obtained: `identity`
 * now calls `POST /api/auth/sign-in/anonymous` and keeps the SESSION COOKIE, where it used to
 * `POST /api/dev/token` and keep a bearer token. The user ids are therefore generated by Better
 * Auth rather than named by the test, so the literal `'user-alice'` assertions became captured
 * ids — the only other change.
 *
 * ⚠️ `--persist-to` A TEMP DIR, NOT `.wrangler/state/`. The suite seeds rows; running it against
 * the developer's own local database would make the second run see the first run's data and pass
 * for the wrong reason. The temp dir also means `pnpm test` never disturbs a dev session.
 */
import { type ChildProcess, execFile, spawn } from 'node:child_process';
import { mkdtempSync, rmSync } from 'node:fs';
import { createRequire } from 'node:module';
import { createServer } from 'node:net';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { promisify } from 'node:util';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { DAILY_WRITE_CEILING, utcDay } from '../middleware/write-guard';

const execFileAsync = promisify(execFile);
const require_ = createRequire(import.meta.url);
const workerRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const wranglerBin = join(dirname(require_.resolve('wrangler/package.json')), 'bin/wrangler.js');

/** A browser origin the worker is configured to allow — the web/desktop builds' stand-in. */
const WEB_ORIGIN = 'http://localhost:8082';

/** The session signing key for this run. Local-only, never leaves this process tree. */
const AUTH_SECRET = 'integration-suite-better-auth-secret-0123456789';

let baseUrl = '';
let child: ChildProcess | undefined;
let persistTo = '';
/** Everything the worker has printed. Scanned for the development OTP line — see `otpFor`. */
let workerOutput = '';

function freePort(): Promise<number> {
  return new Promise((resolve, reject) => {
    const server = createServer();
    server.on('error', reject);
    server.listen(0, '127.0.0.1', () => {
      const address = server.address();
      const port = typeof address === 'object' && address ? address.port : 0;
      server.close(() => resolve(port));
    });
  });
}

async function waitForHealth(url: string, deadlineMs: number): Promise<void> {
  const until = Date.now() + deadlineMs;
  let lastError: unknown;
  while (Date.now() < until) {
    try {
      const res = await fetch(`${url}/health`);
      if (res.ok) return;
    } catch (error) {
      lastError = error;
    }
    await new Promise((r) => setTimeout(r, 250));
  }
  throw new Error(`wrangler dev never became healthy at ${url}: ${String(lastError)}`);
}

beforeAll(async () => {
  persistTo = mkdtempSync(join(tmpdir(), 'cq-d1-'));
  const env = { ...process.env, CI: '1', WRANGLER_SEND_METRICS: 'false' };

  // Real migrations, applied by wrangler — the same command a human runs, against the same
  // generated .sql that is committed. If the migration is wrong, this suite cannot start.
  await execFileAsync(
    process.execPath,
    [wranglerBin, 'd1', 'migrations', 'apply', 'cloud-quran', '--local', '--persist-to', persistTo],
    { cwd: workerRoot, env }
  );

  const port = await freePort();
  baseUrl = `http://127.0.0.1:${port}`;
  child = spawn(
    process.execPath,
    [
      wranglerBin,
      'dev',
      '--local',
      '--persist-to',
      persistTo,
      '--ip',
      '127.0.0.1',
      '--port',
      String(port),
      '--var',
      `BETTER_AUTH_SECRET:${AUTH_SECRET}`,
      // The mailer's development escape hatch: no sending domain exists, so `lib/mail.ts` logs
      // the OTP instead of refusing. Without this the email-otp suite could not read a code.
      '--var',
      'ENVIRONMENT:development',
      // The CORS + trustedOrigins allowlist. Needed by the preflight case at the bottom of this
      // file, and by Better Auth's origin check for any cookie-bearing browser POST.
      '--var',
      `ALLOWED_ORIGINS:${WEB_ORIGIN}`,
    ],
    // ⚠️ PIPED, not ignored. The email-OTP suite reads the code out of the worker's own console
    // output — `lib/mail.ts` logs it in development, because no sending domain exists yet. That
    // is the only way to drive a real sign-in code end to end without inventing a test-only
    // route into the auth server, which is exactly the kind of door this story deleted.
    { cwd: workerRoot, env, stdio: ['ignore', 'pipe', 'pipe'] }
  );
  child.stdout?.on('data', (chunk: Buffer) => {
    workerOutput += chunk.toString();
  });
  child.stderr?.on('data', (chunk: Buffer) => {
    workerOutput += chunk.toString();
  });
  await waitForHealth(baseUrl, 90_000);
});

afterAll(async () => {
  if (child && child.exitCode === null) {
    const exited = new Promise<void>((resolve) => child?.once('exit', () => resolve()));
    child.kill('SIGTERM');
    await Promise.race([exited, new Promise((r) => setTimeout(r, 10_000))]);
    if (child.exitCode === null) child.kill('SIGKILL');
  }
  if (persistTo) rmSync(persistTo, { recursive: true, force: true });
});

/**
 * Seed a row straight into the local database, bypassing the API.
 *
 * ⚠️ This is FIXTURE SQL, not query-layer SQL — the "no raw SQL" boundary is about
 * `src/db/queries.ts` keeping the Postgres escape hatch, and a test that needs to place the write
 * counter at 1,999 has no other way to do it. Driving the ceiling through 2,000 real requests
 * would make the suite unusable, and adding a "lower the ceiling" env var would put a production
 * switch in the worker purely so a test could flip it — the worse of the two.
 */
async function seed(sql: string): Promise<void> {
  await execFileAsync(
    process.execPath,
    [
      wranglerBin,
      'd1',
      'execute',
      'cloud-quran',
      '--local',
      '--persist-to',
      persistTo,
      '--command',
      sql,
    ],
    { cwd: workerRoot, env: { ...process.env, CI: '1', WRANGLER_SEND_METRICS: 'false' } }
  );
}

/**
 * Read one number straight out of the local database.
 *
 * ⚠️ FIXTURE SQL, same carve-out as `seed` above. It exists for the one assertion the HTTP surface
 * structurally cannot make: after a merge the guest USER IS DELETED, so there is no session left
 * to ask "did anything stay behind on them". Rows orphaned on a departed user are invisible to
 * every route and permanent in the table.
 */
async function countRows(sql: string): Promise<number> {
  const { stdout } = await execFileAsync(
    process.execPath,
    [
      wranglerBin,
      'd1',
      'execute',
      'cloud-quran',
      '--local',
      '--persist-to',
      persistTo,
      '--json',
      '--command',
      sql,
    ],
    { cwd: workerRoot, env: { ...process.env, CI: '1', WRANGLER_SEND_METRICS: 'false' } }
  );
  const parsed = JSON.parse(stdout) as { results: Record<string, number>[] }[];
  return Number(Object.values(parsed[0].results[0])[0]);
}

const seedBudget = (userId: string, writes: number) =>
  seed(
    `INSERT OR REPLACE INTO write_budget (user_id, day, writes) VALUES ('${userId}', '${utcDay(Date.now())}', ${writes})`
  );

/**
 * An identity, as the worker now understands one: a session COOKIE plus the user id Better Auth
 * minted for it. `token` keeps its name at the call sites below — every one of them is unchanged
 * from 5-4 — but it now carries a cookie header value rather than a bearer token.
 */
type Identity = { cookie: string; userId: string };

type CallOptions = { method?: string; token?: Identity | string; body?: unknown; origin?: string };

async function call(path: string, { method = 'GET', token, body, origin }: CallOptions = {}) {
  // A raw string is a FORGED credential (the "invalid token" cases below); an Identity is a real
  // session. Both land in the same header, which is the point — the seam must refuse the first.
  const cookie = typeof token === 'string' ? token : token?.cookie;
  const res = await fetch(`${baseUrl}${path}`, {
    method,
    headers: {
      ...(cookie ? { cookie } : {}),
      ...(origin ? { origin } : {}),
      ...(body === undefined ? {} : { 'content-type': 'application/json' }),
    },
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  return { status: res.status, json: (await res.json()) as Record<string, unknown> };
}

/**
 * Mint a real anonymous session — the app's own first-launch call, not a test-only door.
 *
 * ⚠️ Story 5-5: this is the ONE function that moved. Everything below it is identity-agnostic,
 * exactly as the 5-4 header promised. The worker no longer has any route that accepts a user id
 * from a caller, so the id comes back rather than going in.
 */
/**
 * A distinct caller address per identity.
 *
 * ⚠️ NOT A WORKAROUND FOR THE RATE LIMITER — IT IS WHAT THESE TESTS MEAN. Alice and Bob are two
 * different people on two different devices, and `lib/auth.ts` keys the limiter on
 * `cf-connecting-ip` (the un-spoofable header the Cloudflare edge writes; upstream's default
 * `x-forwarded-for` is client-supplied and therefore useless as a key). Without this the whole
 * suite is ONE caller hammering `/sign-in/anonymous`, which upstream limits to 3 per 10s — so
 * the fourth identity 429s and a dozen unrelated tests fail for a reason none of them is about.
 * The ceiling itself is asserted deliberately, from one address, in its own describe below.
 */
let callerSeq = 0;
function nextCallerIp(): string {
  callerSeq += 1;
  return `203.0.113.${callerSeq % 250}`;
}

async function identity(): Promise<Identity> {
  const res = await fetch(`${baseUrl}/api/auth/sign-in/anonymous`, {
    method: 'POST',
    headers: { 'content-type': 'application/json', 'cf-connecting-ip': nextCallerIp() },
    body: '{}',
  });
  const setCookie = res.headers.get('set-cookie');
  if (!setCookie) throw new Error(`no session cookie from anonymous sign-in (${res.status})`);
  const body = (await res.json()) as { user?: { id?: string } };
  const userId = body.user?.id;
  if (!userId) throw new Error(`anonymous sign-in returned no user (${res.status})`);
  return { cookie: setCookie.split(';')[0], userId };
}

const position = (updatedAt: number, surah: number) => ({
  surah,
  verse: 1,
  page: surah,
  mode: 'reading' as const,
  updatedAt,
});
const audio = (updatedAt: number, surah: number) => ({
  surah,
  verse: 1,
  reciterId: 'alafasy',
  updatedAt,
});
const prefs = (updatedAt: number, fontSize: number) => ({
  theme: 'sepia' as const,
  fontSize,
  reciterId: 'alafasy',
  readingMode: 'mushaf' as const,
  translationId: null,
  speedRate: 1.25,
  transliteration: false,
  updatedAt,
});

let alice: Identity;
let bob: Identity;

beforeAll(async () => {
  alice = await identity();
  bob = await identity();
  expect(alice.userId).toBeTypeOf('string');
  expect(bob.userId).toBeTypeOf('string');
  expect(alice.userId).not.toBe(bob.userId);
  expect(alice.cookie).not.toBe(bob.cookie);
});

describe('no identity', () => {
  const routes: [string, string, unknown][] = [
    ['GET', '/api/sync/reading-position', undefined],
    ['PUT', '/api/sync/reading-position', position(1, 1)],
    ['GET', '/api/sync/preferences', undefined],
    ['PUT', '/api/sync/preferences', prefs(1, 20)],
    ['GET', '/api/sync/audio-position', undefined],
    ['PUT', '/api/sync/audio-position', audio(1, 1)],
    ['GET', '/api/sync/bookmarks', undefined],
    ['POST', '/api/sync/bookmarks', { id: 'anon', surah: 1, verse: 1, createdAt: 1 }],
    ['DELETE', '/api/sync/bookmarks/anon', undefined],
  ];

  it.each(
    routes
  )('%s %s answers 401, not 500 — anonymous is the app normal state', async (method, path, body) => {
    const { status, json } = await call(path, { method, body });
    expect(status).toBe(401);
    expect(json).toEqual({ ok: false, error: 'unauthorized' });
  });

  it('an INVALID credential is refused exactly like none', async () => {
    // The 5-4 shape of this case was a malformed bearer token; the intent — garbage in the
    // credential position must 401, never 500 — is what survives the move to cookies.
    const { status } = await call('/api/sync/reading-position', {
      token: 'better-auth.session_token=not.a.real.token',
    });
    expect(status).toBe(401);
  });

  it('a TAMPERED session cookie is refused — the signature is checked, not just carried', async () => {
    // Alice's cookie with its signature half replaced. Better Auth's token is
    // `<id>.<hmac>`; corrupting the hmac must not authenticate her.
    const [name, value] = alice.cookie.split('=');
    const [id] = decodeURIComponent(value).split('.');
    const forged = `${name}=${encodeURIComponent(`${id}.AAAAAAAAAAAAAAAAAAAAAAAAAAAA`)}`;
    const { status } = await call('/api/sync/reading-position', { token: forged });
    expect(status).toBe(401);
  });

  it('a story 5-4 DEV BEARER TOKEN is refused, and its issuer is gone', async () => {
    // The issuer, the verifier and the route were deleted rather than disabled, so this is not
    // "the gate is closed" — there is nothing left that could open it.
    const bearer = await fetch(`${baseUrl}/api/sync/reading-position`, {
      headers: { authorization: 'Bearer eyJzdWIiOiJ1c2VyLWFsaWNlIn0.AAAA' },
    });
    expect(bearer.status).toBe(401);
    const issuer = await fetch(`${baseUrl}/api/dev/token`, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ userId: 'user-alice' }),
    });
    expect(issuer.status).toBe(404);
  });

  it('and none of that wrote a row — Alice still sees nothing', async () => {
    const { json } = await call('/api/sync/reading-position', { token: alice });
    expect(json).toEqual({ ok: true, position: null });
  });
});

describe('cross-user isolation — READS', () => {
  beforeAll(async () => {
    await call('/api/sync/reading-position', {
      method: 'PUT',
      token: alice,
      body: position(2000, 2),
    });
    await call('/api/sync/preferences', { method: 'PUT', token: alice, body: prefs(2000, 44) });
    await call('/api/sync/audio-position', { method: 'PUT', token: alice, body: audio(2000, 2) });
    await call('/api/sync/bookmarks', {
      method: 'POST',
      token: alice,
      body: { id: 'bm-alice', surah: 2, verse: 255, label: 'Ayat al-Kursi', createdAt: 2000 },
    });
  });

  it('Alice reads her own rows', async () => {
    const { json } = await call('/api/sync/reading-position', { token: alice });
    expect(json.position).toMatchObject({ userId: alice.userId, surah: 2 });
  });

  it('Bob cannot read Alice reading position', async () => {
    const { json } = await call('/api/sync/reading-position', { token: bob });
    expect(json).toEqual({ ok: true, position: null });
  });

  it('Bob cannot read Alice preferences', async () => {
    const { json } = await call('/api/sync/preferences', { token: bob });
    expect(json).toEqual({ ok: true, preferences: null });
  });

  it('Bob cannot read Alice audio position', async () => {
    const { json } = await call('/api/sync/audio-position', { token: bob });
    expect(json).toEqual({ ok: true, audioPosition: null });
  });

  it('Bob cannot read Alice bookmarks', async () => {
    const { json } = await call('/api/sync/bookmarks', { token: bob });
    expect(json).toEqual({ ok: true, bookmarks: [] });
  });
});

describe('cross-user isolation — WRITES (the half a read-only denial misses)', () => {
  it('Bob writing his own position does not touch Alice row', async () => {
    await call('/api/sync/reading-position', {
      method: 'PUT',
      token: bob,
      body: position(9000, 114),
    });
    const mine = await call('/api/sync/reading-position', { token: bob });
    expect(mine.json.position).toMatchObject({ userId: bob.userId, surah: 114 });
    const hers = await call('/api/sync/reading-position', { token: alice });
    expect(hers.json.position).toMatchObject({ userId: alice.userId, surah: 2 });
  });

  it('Bob writing preferences and audio position does not touch Alice rows', async () => {
    await call('/api/sync/preferences', { method: 'PUT', token: bob, body: prefs(9000, 20) });
    await call('/api/sync/audio-position', { method: 'PUT', token: bob, body: audio(9000, 114) });
    const prefsOfAlice = await call('/api/sync/preferences', { token: alice });
    expect(prefsOfAlice.json.preferences).toMatchObject({ userId: alice.userId, fontSize: 44 });
    const audioOfAlice = await call('/api/sync/audio-position', { token: alice });
    expect(audioOfAlice.json.audioPosition).toMatchObject({ userId: alice.userId, surah: 2 });
  });

  it('Bob CANNOT delete Alice bookmark by id — the one route where a client names a row', async () => {
    const { status, json } = await call('/api/sync/bookmarks/bm-alice', {
      method: 'DELETE',
      token: bob,
    });
    expect(status).toBe(200);
    expect(json).toEqual({ ok: true, deleted: false });
    const stillThere = await call('/api/sync/bookmarks', { token: alice });
    expect(stillThere.json.bookmarks).toHaveLength(1);
  });

  it('Bob CANNOT hijack Alice bookmark id, and learns nothing about her row', async () => {
    const { status, json } = await call('/api/sync/bookmarks', {
      method: 'POST',
      token: bob,
      body: { id: 'bm-alice', surah: 9, verse: 9, createdAt: 9000 },
    });
    expect(status).toBe(409);
    expect(JSON.stringify(json)).not.toContain('Ayat al-Kursi');
    expect(JSON.stringify(json)).not.toContain(alice.userId);
    const hers = await call('/api/sync/bookmarks', { token: alice });
    expect(hers.json.bookmarks).toMatchObject([{ id: 'bm-alice', surah: 2, verse: 255 }]);
  });

  it('Alice deleting her OWN bookmark works — the denial is not a blanket refusal', async () => {
    const { json } = await call('/api/sync/bookmarks/bm-alice', { method: 'DELETE', token: alice });
    expect(json).toEqual({ ok: true, deleted: true });
    const after = await call('/api/sync/bookmarks', { token: alice });
    expect(after.json.bookmarks).toEqual([]);
  });
});

describe('last-write-wins, and the write budget it protects', () => {
  it('an OLDER updatedAt writes no row and leaves the stored row alone', async () => {
    const stale = await call('/api/sync/reading-position', {
      method: 'PUT',
      token: alice,
      body: position(1000, 100),
    });
    expect(stale.json).toEqual({ ok: true, applied: false });
    const { json } = await call('/api/sync/reading-position', { token: alice });
    expect(json.position).toMatchObject({ surah: 2, updatedAt: 2000 });
  });

  it('an IDENTICAL updatedAt is also a no-op — a burst re-sending one instant costs one write', async () => {
    for (let i = 0; i < 4; i++) {
      const { json } = await call('/api/sync/reading-position', {
        method: 'PUT',
        token: alice,
        body: position(2000, 3),
      });
      expect(json).toEqual({ ok: true, applied: false });
    }
    const { json } = await call('/api/sync/reading-position', { token: alice });
    expect(json.position).toMatchObject({ surah: 2 });
  });

  it('a NEWER updatedAt applies', async () => {
    const { json } = await call('/api/sync/reading-position', {
      method: 'PUT',
      token: alice,
      body: position(3000, 18),
    });
    expect(json).toEqual({ ok: true, applied: true });
  });

  it('preferences and audio position obey the same rule', async () => {
    expect(
      (await call('/api/sync/preferences', { method: 'PUT', token: alice, body: prefs(1000, 20) }))
        .json
    ).toEqual({ ok: true, applied: false });
    expect(
      (
        await call('/api/sync/audio-position', {
          method: 'PUT',
          token: alice,
          body: audio(1000, 5),
        })
      ).json
    ).toEqual({ ok: true, applied: false });
  });
});

describe('bookmarks union-merge', () => {
  it('the same (user, surah, verse) twice is idempotent — one row, second write is a no-op', async () => {
    const first = await call('/api/sync/bookmarks', {
      method: 'POST',
      token: alice,
      body: { id: 'dup-1', surah: 36, verse: 1, label: 'Ya-Sin', createdAt: 1000 },
    });
    expect(first.json).toMatchObject({ ok: true, created: true });

    // A second device, offline, minted its own id for the same ayah.
    const second = await call('/api/sync/bookmarks', {
      method: 'POST',
      token: alice,
      body: { id: 'dup-2', surah: 36, verse: 1, label: 'different label', createdAt: 2000 },
    });
    expect(second.json).toMatchObject({ ok: true, created: false });
    expect((second.json.bookmark as { id: string }).id).toBe('dup-1');

    const list = await call('/api/sync/bookmarks', { token: alice });
    expect(list.json.bookmarks).toHaveLength(1);
  });
});

describe('validation', () => {
  it('rejects out-of-range values with 422 and writes nothing', async () => {
    const { status, json } = await call('/api/sync/preferences', {
      method: 'PUT',
      token: bob,
      body: { ...prefs(99_000, 4000) },
    });
    expect(status).toBe(422);
    expect(json.error).toContain('fontSize');
    const after = await call('/api/sync/preferences', { token: bob });
    expect(after.json.preferences).toMatchObject({ fontSize: 20 });
  });

  it('rejects a non-JSON body with 422 rather than a 500', async () => {
    const res = await fetch(`${baseUrl}/api/sync/reading-position`, {
      method: 'PUT',
      headers: { cookie: bob.cookie, 'content-type': 'application/json' },
      body: 'not json',
    });
    expect(res.status).toBe(422);
  });
});

describe('the per-user daily write ceiling', () => {
  // ⚠️ The ceiling is the only thing standing between a render-storm defect and an unbounded
  // bill. (This read "an account-wide outage — D1's free tier returns ERRORS past 100k rows/day,
  // it does not bill"; the account is on Workers Paid, where it bills. Corrected 2026-08-24,
  // story 5-5 — the ceiling and its size are unchanged.) An untested ceiling is the same class
  // of thing as the ownership rule that matched nothing.

  it('refuses with 429 at the ceiling, and writes NOTHING', async () => {
    const carol = await identity();
    await seedBudget(carol.userId, DAILY_WRITE_CEILING);

    const refused = await call('/api/sync/reading-position', {
      method: 'PUT',
      token: carol,
      body: position(5000, 7),
    });
    expect(refused.status).toBe(429);
    expect(refused.json).toEqual({ ok: false, error: 'daily-write-ceiling-reached' });

    // The rejection happens BEFORE the write, so nothing landed — and the rejection itself cost
    // no rows either, which is the point: a runaway client past its ceiling is free, not linear.
    const after = await call('/api/sync/reading-position', { token: carol });
    expect(after.json).toEqual({ ok: true, position: null });
  });

  it('an APPLIED write spends exactly one unit of budget', async () => {
    const dave = await identity();
    await seedBudget(dave.userId, DAILY_WRITE_CEILING - 1);

    const allowed = await call('/api/sync/reading-position', {
      method: 'PUT',
      token: dave,
      body: position(5000, 7),
    });
    expect(allowed.json).toEqual({ ok: true, applied: true });

    // That one write took the counter to the ceiling.
    const refused = await call('/api/sync/reading-position', {
      method: 'PUT',
      token: dave,
      body: position(6000, 8),
    });
    expect(refused.status).toBe(429);
  });

  it('a NO-OP write spends NO budget — the whole reason the counter is recorded after the fact', async () => {
    const erin = await identity();
    await call('/api/sync/reading-position', {
      method: 'PUT',
      token: erin,
      body: position(5000, 7),
    });
    await seedBudget(erin.userId, DAILY_WRITE_CEILING - 1);

    // An older timestamp: the upsert matches nothing, so no row is written...
    const noop = await call('/api/sync/reading-position', {
      method: 'PUT',
      token: erin,
      body: position(4000, 9),
    });
    expect(noop.json).toEqual({ ok: true, applied: false });

    // ...and the one remaining unit of budget is therefore still there.
    const stillAllowed = await call('/api/sync/reading-position', {
      method: 'PUT',
      token: erin,
      body: position(6000, 8),
    });
    expect(stillAllowed.json).toEqual({ ok: true, applied: true });
  });

  it('one user hitting the ceiling does not block another', async () => {
    const frank = await identity();
    await seedBudget(frank.userId, DAILY_WRITE_CEILING);
    expect(
      (
        await call('/api/sync/reading-position', {
          method: 'PUT',
          token: frank,
          body: position(1, 1),
        })
      ).status
    ).toBe(429);
    // Alice, from the suites above, is nowhere near her own ceiling.
    expect(
      (
        await call('/api/sync/reading-position', {
          method: 'PUT',
          token: alice,
          body: position(50_000, 12),
        })
      ).json
    ).toEqual({ ok: true, applied: true });
  });
});

describe("the anonymous → signed-in upgrade carries the guest's rows", () => {
  // ⚠️ THIS IS THE HARD HALF OF THE UPGRADE, NOT THE EASY ONE. The 5-5 spike proved that
  // `linkSocial({ idToken })` — the path the app uses for Apple and Google — keeps the SAME
  // `user.id`, so there is nothing to migrate there and nothing that can orphan. Email OTP is
  // the case where Better Auth genuinely mints a DIFFERENT user and then deletes the anonymous
  // one, which is where rows are lost if `onLinkAccount` does not move them. Apple and Google
  // cannot be driven from here at all: their id tokens are signed by Apple and Google.

  /**
   * Read the NEXT code the worker logs for `email`, waiting for it to arrive on stdout.
   *
   * ⚠️ THE CURSOR IS NOT AN OPTIMISATION. `workerOutput` accumulates for the whole run, so a
   * scan from the start returns the FIRST code ever printed for that address — meaning a second
   * request for the same address silently hands back the stale (already-consumed) code, and the
   * wrong-code cases below start depending on which test ran first. Consuming past each match
   * makes every call answer the request that provoked it.
   */
  let otpCursor = 0;
  async function otpFor(email: string): Promise<string> {
    const pattern = new RegExp(`email OTP for ${email}: (\\d{6})`, 'g');
    const until = Date.now() + 15_000;
    while (Date.now() < until) {
      pattern.lastIndex = otpCursor;
      const match = pattern.exec(workerOutput);
      if (match) {
        otpCursor = match.index + match[0].length;
        return match[1];
      }
      await new Promise((r) => setTimeout(r, 100));
    }
    throw new Error(`no OTP logged for ${email} after offset ${otpCursor}`);
  }

  async function authPost(path: string, cookie: string | undefined, body: unknown) {
    const res = await fetch(`${baseUrl}/api/auth${path}`, {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        // One caller per call — see `nextCallerIp`. `/email-otp/send-verification-otp` is limited
        // to 3 per 60s per address by upstream, which two upgrade tests would otherwise share.
        'cf-connecting-ip': nextCallerIp(),
        // ⚠️ REQUIRED ON EVERY COOKIE-BEARING AUTH POST. Better Auth refuses one with no Origin
        // (`MISSING_OR_NULL_ORIGIN`), and the native client supplies it as `expo-origin`, which
        // `@better-auth/expo`'s server half promotes. `cloud-quran://` is in `trustedOrigins`.
        ...(cookie ? { cookie, origin: 'cloud-quran://' } : {}),
      },
      body: JSON.stringify(body),
    });
    const setCookie = res.headers.get('set-cookie');
    return {
      status: res.status,
      json: (await res.json()) as Record<string, unknown>,
      cookie: setCookie ? setCookie.split(';')[0] : null,
    };
  }

  /** Sign `guest` in to `email`, returning the identity they end up as. */
  async function upgrade(guest: Identity, email: string): Promise<Identity> {
    const sent = await authPost('/email-otp/send-verification-otp', guest.cookie, {
      email,
      type: 'sign-in',
    });
    expect(sent.status).toBe(200);
    const signedIn = await authPost('/sign-in/email-otp', guest.cookie, {
      email,
      otp: await otpFor(email),
    });
    expect(signedIn.status).toBe(200);
    expect(signedIn.cookie).toBeTruthy();
    return {
      cookie: signedIn.cookie as string,
      userId: (signedIn.json.user as { id: string }).id,
    };
  }

  /** The account the first upgrade lands in — the destination the second guest must MERGE into. */
  let accountUserId = '';

  it('a guest carries ALL FOUR entity kinds across an email sign-in', async () => {
    // ⚠️ ALL FOUR, DELIBERATELY. `reassignUserRows` copies each of the three single-row tables
    // behind an `if (row)` but deletes them all unconditionally, so a guest holding only a
    // reading position exercises one copy branch and three deletes — and removing either of the
    // other two copy blocks would leave the suite green while a real reader's preferences and
    // audio position were DESTROYED rather than moved.
    const guest = await identity();
    await call('/api/sync/reading-position', {
      method: 'PUT',
      token: guest,
      body: position(7000, 55),
    });
    await call('/api/sync/preferences', { method: 'PUT', token: guest, body: prefs(7000, 32) });
    await call('/api/sync/audio-position', { method: 'PUT', token: guest, body: audio(7000, 55) });
    await call('/api/sync/bookmarks', {
      method: 'POST',
      token: guest,
      body: { id: 'bm-guest', surah: 55, verse: 13, label: 'Ar-Rahman', createdAt: 7000 },
    });

    const upgraded = await upgrade(guest, 'guest-upgrade@example.com');

    // A different principal — this is the path that mints one, which is why the re-stamp exists.
    expect(upgraded.userId).not.toBe(guest.userId);
    accountUserId = upgraded.userId;

    const stayed = await call('/api/sync/reading-position', { token: upgraded });
    expect(stayed.json.position).toMatchObject({ userId: upgraded.userId, surah: 55 });
    const movedPrefs = await call('/api/sync/preferences', { token: upgraded });
    expect(movedPrefs.json.preferences).toMatchObject({ userId: upgraded.userId, fontSize: 32 });
    const movedAudio = await call('/api/sync/audio-position', { token: upgraded });
    expect(movedAudio.json.audioPosition).toMatchObject({ userId: upgraded.userId, surah: 55 });
    const marks = await call('/api/sync/bookmarks', { token: upgraded });
    expect(marks.json.bookmarks).toMatchObject([{ id: 'bm-guest', surah: 55, verse: 13 }]);

    // ...and nothing was left behind on the deleted guest either.
    const orphan = await call('/api/sync/reading-position', { token: guest });
    expect(orphan.status).toBe(401);
  });

  it('a SECOND guest merging into the same account: newer wins, duplicates drop', async () => {
    // The destination now already HAS rows — the case the first test cannot reach, because an
    // email sign-in that mints a brand-new user always merges into an empty one. Two branches
    // live only here: the LWW guard (`setWhere: lt(updatedAt, incoming)`), and the drop of a
    // guest bookmark whose (surah, verse) the destination already holds — without which the
    // colliding UPDATE hits the unique index and fails the WHOLE `db.batch()`, taking the
    // reading position and preferences down with it.
    const email = 'guest-upgrade@example.com';
    const second = await identity();
    // OLDER than the row already stored (7000), so last-write-wins must keep the stored one.
    await call('/api/sync/reading-position', {
      method: 'PUT',
      token: second,
      body: position(3000, 2),
    });
    // OLDER too — the fourth entity kind, and the one the first cut of this test left out, so
    // `reassignUserRows`'s preferences branch was only ever driven into an EMPTY destination.
    await call('/api/sync/preferences', { method: 'PUT', token: second, body: prefs(3000, 20) });
    // NEWER, so this one must win.
    await call('/api/sync/audio-position', { method: 'PUT', token: second, body: audio(9000, 36) });
    // The same ayah the first guest already bookmarked, under a different client-minted id.
    await call('/api/sync/bookmarks', {
      method: 'POST',
      token: second,
      body: { id: 'bm-second-dup', surah: 55, verse: 13, label: 'duplicate', createdAt: 8000 },
    });
    // ...plus one the destination does not have, which must survive.
    await call('/api/sync/bookmarks', {
      method: 'POST',
      token: second,
      body: { id: 'bm-second-new', surah: 36, verse: 1, label: 'Ya-Sin', createdAt: 8000 },
    });

    const merged = await upgrade(second, email);

    // ⚠️ ONE HUMAN, ONE ACCOUNT. The second guest must land in the account the FIRST one created,
    // not a third user. A fork here is the production defect this amendment exists to fix, and it
    // is the assertion nothing else in the suite makes.
    expect(merged.userId).toBe(accountUserId);

    const readingPosition = await call('/api/sync/reading-position', { token: merged });
    // The destination's newer row survived an older incoming one.
    expect(readingPosition.json.position).toMatchObject({ surah: 55, updatedAt: 7000 });
    const preferences = await call('/api/sync/preferences', { token: merged });
    // ...and so did its preferences, which the incoming older row must not overwrite.
    expect(preferences.json.preferences).toMatchObject({ fontSize: 32, updatedAt: 7000 });
    const audioPosition = await call('/api/sync/audio-position', { token: merged });
    // ...and the newer incoming one replaced the destination's.
    expect(audioPosition.json.audioPosition).toMatchObject({ surah: 36, updatedAt: 9000 });

    const bookmarks = (await call('/api/sync/bookmarks', { token: merged })).json.bookmarks as {
      id: string;
      label: string | null;
    }[];
    expect(bookmarks).toHaveLength(2);
    // The DESTINATION's row is the survivor of the collision — label and all.
    expect(bookmarks.find((b) => b.id === 'bm-guest')?.label).toBe('Ar-Rahman');
    expect(bookmarks.some((b) => b.id === 'bm-second-dup')).toBe(false);
    expect(bookmarks.some((b) => b.id === 'bm-second-new')).toBe(true);

    // ⚠️ AND THE DROPPED DUPLICATE IS GONE FROM THE TABLE, NOT MERELY ABSENT FROM THE ACCOUNT.
    // `reassignUserRows` skips a colliding bookmark when it re-stamps, so without the explicit
    // DELETE the row simply STAYS on the guest — who is deleted moments later — and becomes a
    // permanent row owned by nobody, invisible to every route and billed for forever. Asserting
    // only the account's list cannot see that: a mutation removing the DELETE left this whole
    // suite green. There is no FK from `bookmarks` to `user`, so nothing cascades it away.
    expect(await countRows(`SELECT COUNT(*) AS n FROM bookmarks WHERE id = 'bm-second-dup'`)).toBe(
      0
    );
    expect(
      await countRows(`SELECT COUNT(*) AS n FROM bookmarks WHERE user_id = '${second.userId}'`)
    ).toBe(0);
  });

  it('a THIRD guest adds what the account lacks and never forks', async () => {
    // The complement of the case above: the incoming rows are NEWER, so every one of them must
    // land — proving the merge is a merge in both directions rather than "the destination always
    // wins", which the previous case alone could not distinguish.
    const third = await identity();
    await call('/api/sync/reading-position', {
      method: 'PUT',
      token: third,
      body: position(99_000, 18),
    });
    await call('/api/sync/preferences', { method: 'PUT', token: third, body: prefs(99_000, 44) });
    await call('/api/sync/bookmarks', {
      method: 'POST',
      token: third,
      body: { id: 'bm-third', surah: 18, verse: 10, label: 'Al-Kahf', createdAt: 99_000 },
    });

    const merged = await upgrade(third, 'guest-upgrade@example.com');
    expect(merged.userId).toBe(accountUserId);

    expect(
      (await call('/api/sync/reading-position', { token: merged })).json.position
    ).toMatchObject({ surah: 18, updatedAt: 99_000 });
    expect((await call('/api/sync/preferences', { token: merged })).json.preferences).toMatchObject(
      {
        fontSize: 44,
        updatedAt: 99_000,
      }
    );
    const bookmarks = (await call('/api/sync/bookmarks', { token: merged })).json.bookmarks as {
      id: string;
    }[];
    // Union: the account's two survive AND the newcomer's is added.
    expect(bookmarks.map((b) => b.id).sort()).toEqual(['bm-guest', 'bm-second-new', 'bm-third']);
  });

  it('a wrong code is a typed 4xx, never a 500', async () => {
    const wrong = await authPost('/sign-in/email-otp', undefined, {
      email: 'guest-upgrade@example.com',
      otp: '000000',
    });
    expect(wrong.status).toBeLessThan(500);
    expect(wrong.status).toBeGreaterThanOrEqual(400);
    expect(wrong.json.code).toBe('INVALID_OTP');
  });

  it('an unknown address is refused identically — no account enumeration', async () => {
    const unknown = await authPost('/sign-in/email-otp', undefined, {
      email: 'nobody-at-all@example.com',
      otp: '000000',
    });
    expect(unknown.status).toBeGreaterThanOrEqual(400);
    expect(unknown.json.code).toBe('INVALID_OTP');
  });
});

describe('the browser contract — CORS, and the credentials flag that IS the web session', () => {
  // ⚠️ THIS SUITE IS NATIVE-SHAPED EVERYWHERE ELSE, WHICH IS EXACTLY WHY THIS BLOCK EXISTS. Every
  // other request here is a bare `fetch` with a hand-set cookie: no preflight, no Origin, no
  // browser rules. Deleting `credentials: true` from `app.ts` therefore passed all 38 of them
  // while the web and Electron builds — two of this app's four platforms — could not hold a
  // session at all, because a browser attaches no cookie to a cross-origin request without it.

  const preflight = (origin: string) =>
    fetch(`${baseUrl}/api/sync/reading-position`, {
      method: 'OPTIONS',
      headers: {
        origin,
        'access-control-request-method': 'GET',
        'access-control-request-headers': 'content-type',
      },
    });

  it('an allowed origin gets the credentials flag back — without it the web build has no session', async () => {
    const res = await preflight(WEB_ORIGIN);
    expect(res.status).toBeLessThan(300);
    expect(res.headers.get('access-control-allow-origin')).toBe(WEB_ORIGIN);
    // The one header doing the work. `Cookie` and `Set-Cookie` are FORBIDDEN header names, which
    // no `allowHeaders`/`exposeHeaders` entry can change; this is what makes the browser send its
    // jar and store what comes back.
    expect(res.headers.get('access-control-allow-credentials')).toBe('true');
  });

  it('an origin that is NOT on the allowlist is refused — never a wildcard', async () => {
    const res = await preflight('https://evil.example.com');
    expect(res.headers.get('access-control-allow-origin')).toBeNull();
    // `credentials: true` is only safe because the origin is an explicit allowlist. A `*` here
    // with credentials on would be a browser-enforced error anyway — and a design error first.
    expect(res.headers.get('access-control-allow-origin')).not.toBe('*');
  });

  it('the auth routes are inside the same CORS scope, not bolted on beside it', async () => {
    // `/api/auth/*` is mounted INSIDE the app chain so it inherits this middleware. Mounted as a
    // separate router it would skip CORS entirely and every browser sign-in would fail.
    const res = await fetch(`${baseUrl}/api/auth/get-session`, {
      method: 'OPTIONS',
      headers: {
        origin: WEB_ORIGIN,
        'access-control-request-method': 'GET',
        'access-control-request-headers': 'content-type',
      },
    });
    expect(res.headers.get('access-control-allow-origin')).toBe(WEB_ORIGIN);
    expect(res.headers.get('access-control-allow-credentials')).toBe('true');
  });
});

describe('the rate limiter, from ONE address', () => {
  // ⚠️ WHAT THIS PINS IS `enabled`, AND ONLY THAT. Better Auth turns rate limiting on in
  // PRODUCTION ONLY, so before `lib/auth.ts` set `enabled: true` every non-production deployment
  // had no ceiling at all on the unauthenticated OTP send — the path that mails arbitrary
  // addresses from this project's own domain. Removing that line reddens this test.
  //
  // ⚠️ IT DOES NOT PIN `storage: 'database'`, AND NO TEST HERE CAN. A local `wrangler dev` is a
  // single isolate, where the module-scope memory backend behaves identically to the table.
  // Switching the storage back passes this suite; see the note in `lib/auth.ts` for why the table
  // is still the right choice, and `deferred-work.md` for the gap.
  //
  // Every other test in this file deliberately arrives from a DIFFERENT address (`nextCallerIp`),
  // so this is the only place the ceiling is allowed to fire.

  it('refuses a burst of anonymous sign-ups from one caller with 429', async () => {
    const ip = '198.51.100.7';
    const attempt = () =>
      fetch(`${baseUrl}/api/auth/sign-in/anonymous`, {
        method: 'POST',
        headers: { 'content-type': 'application/json', 'cf-connecting-ip': ip },
        body: '{}',
      });

    const statuses: number[] = [];
    // Upstream limits every `/sign-in*` path to 3 per 10 seconds; six attempts must not all pass.
    for (let i = 0; i < 6; i++) statuses.push((await attempt()).status);

    expect(statuses).toContain(429);
    // Anti-vacuity: the ceiling must let the first few THROUGH, or this would also pass against a
    // worker that had simply broken anonymous sign-in.
    expect(statuses.filter((status) => status === 200).length).toBeGreaterThan(0);
  });

  it('a different caller is unaffected by that burst', async () => {
    const res = await fetch(`${baseUrl}/api/auth/sign-in/anonymous`, {
      method: 'POST',
      headers: { 'content-type': 'application/json', 'cf-connecting-ip': '198.51.100.99' },
      body: '{}',
    });
    expect(res.status).toBe(200);
  });
});

describe('the data lifecycle — export, purge and account deletion (story 5-7)', () => {
  /**
   * ⚠️ THESE RUN LAST, AND THEY MINT THEIR OWN IDENTITIES. Every case below DESTROYS rows, so
   * reusing `alice` or `bob` would silently empty the fixtures the earlier describes built — the
   * "mutable fixture state carried across describe blocks" hazard this suite already records, in
   * its most damaging form. Each case owns a guest nobody else touches.
   */

  /** A caller with all four entity kinds populated, so a purge has something of each to destroy. */
  async function populated(): Promise<Identity> {
    const who = await identity();
    await call('/api/sync/reading-position', {
      method: 'PUT',
      token: who,
      body: position(9000, 3),
    });
    await call('/api/sync/preferences', { method: 'PUT', token: who, body: prefs(9000, 28) });
    await call('/api/sync/audio-position', { method: 'PUT', token: who, body: audio(9000, 3) });
    await call('/api/sync/bookmarks', {
      method: 'POST',
      token: who,
      body: { id: `bm-${who.userId}`, surah: 3, verse: 190, label: 'Al Imran', createdAt: 9000 },
    });
    return who;
  }

  /** Every synced surface at once, so "nothing left behind" is one assertion rather than four. */
  async function readAll(who: Identity) {
    const [reading, preferences, audioPosition, bookmarks] = await Promise.all([
      call('/api/sync/reading-position', { token: who }),
      call('/api/sync/preferences', { token: who }),
      call('/api/sync/audio-position', { token: who }),
      call('/api/sync/bookmarks', { token: who }),
    ]);
    return {
      reading: reading.json.position,
      preferences: preferences.json.preferences,
      audioPosition: audioPosition.json.audioPosition,
      bookmarks: bookmarks.json.bookmarks,
    };
  }

  describe('GET /api/account/export', () => {
    it('returns exactly the caller rows, in a self-describing envelope', async () => {
      const who = await populated();
      const { status, json } = await call('/api/account/export', { token: who });
      expect(status).toBe(200);
      const doc = json.export as Record<string, unknown>;
      expect(doc.format).toBe('cloud-quran-export');
      expect(doc.version).toBe(1);
      expect(typeof doc.exportedAt).toBe('string');
      expect(doc.account).toMatchObject({ id: who.userId, isAnonymous: true });
      expect(doc.readingPosition).toMatchObject({ userId: who.userId, surah: 3 });
      expect(doc.preferences).toMatchObject({ userId: who.userId, fontSize: 28 });
      expect(doc.audioPosition).toMatchObject({ userId: who.userId, surah: 3 });
      expect(doc.bookmarks).toMatchObject([{ surah: 3, verse: 190, label: 'Al Imran' }]);
    });

    it('NAMES the linked providers, with a parseable date and no credential', async () => {
      // ⚠️ THE `providers` MAPPING WAS ASSERTED NOWHERE, so replacing it with `[]` was green:
      // the credential case below only proves what is ABSENT, and the client suite compares the
      // export against its own fixture. A linked provider IS personal data ("you signed in with
      // Apple, on this date"), so the export owes the reader both halves.
      //
      // Seeded with fixture SQL — the same carve-out `seedBudget` uses. Driving a real provider
      // link would need an id token signed by Apple or Google, which is the gap this suite has
      // recorded since story 5-5.
      const who = await identity();
      const linkedAt = Date.UTC(2026, 0, 2, 3, 4, 5);
      await seed(
        `INSERT INTO account (id, issuer, account_id, provider_id, user_id, access_token, ` +
          `refresh_token, id_token, password, created_at, updated_at) VALUES ` +
          `('acct-${who.userId}', 'https://appleid.apple.com', 'apple-sub-1', 'apple', ` +
          `'${who.userId}', 'ACCESS-SECRET', 'REFRESH-SECRET', 'ID-SECRET', 'PASSWORD-SECRET', ` +
          `${linkedAt}, ${linkedAt})`
      );

      const { json } = await call('/api/account/export', { token: who });
      const doc = json.export as Record<string, unknown>;
      expect(doc.providers).toEqual([
        { providerId: 'apple', linkedAt: new Date(linkedAt).toISOString() },
      ]);
      // The date is a real ISO-8601 instant, not `[object Object]` or a raw millisecond number.
      const [provider] = doc.providers as { linkedAt: string }[];
      expect(Number.isNaN(Date.parse(provider.linkedAt))).toBe(false);
      // ...and none of the four credential columns rode along with it.
      const serialized = JSON.stringify(doc);
      for (const secret of ['ACCESS-SECRET', 'REFRESH-SECRET', 'ID-SECRET', 'PASSWORD-SECRET']) {
        expect(serialized).not.toContain(secret);
      }
    });

    it('reports a COMPLETE bookmark set as complete', async () => {
      // Anti-vacuity for the bound: `bookmarksTruncated` must be capable of being false, or the
      // flag would be a constant and the limit unobservable.
      const who = await populated();
      const { json } = await call('/api/account/export', { token: who });
      expect((json.export as Record<string, unknown>).bookmarksTruncated).toBe(false);
    });

    it('NEVER carries a provider credential — the account row holds tokens the export must not', async () => {
      // ⚠️ THE REASON THE EXPORT NAMES ITS COLUMNS INSTEAD OF `select()`-ing THE ROW. `account`
      // stores `accessToken` / `refreshToken` / `idToken` / `password`; those belong to a
      // provider, not to the reader, and handing them to a share sheet is a capability leak. A
      // `select()` over the whole table would ship them and typecheck perfectly.
      const who = await populated();
      const { json } = await call('/api/account/export', { token: who });
      const serialized = JSON.stringify(json.export);
      for (const forbidden of ['accessToken', 'refreshToken', 'idToken', 'password']) {
        expect(serialized).not.toContain(forbidden);
      }
    });

    it("shows a caller NOTHING of another caller's rows", async () => {
      // The whole authorization model in one case: there is no user id in the path, the query or
      // a body, so "export somebody else" is not a request this worker can express. A fresh guest
      // with nothing of their own gets an empty document, not Alice's.
      const stranger = await identity();
      const { status, json } = await call('/api/account/export', { token: stranger });
      expect(status).toBe(200);
      const doc = json.export as Record<string, unknown>;
      expect(doc.account).toMatchObject({ id: stranger.userId });
      expect(doc.readingPosition).toBeNull();
      expect(doc.preferences).toBeNull();
      expect(doc.audioPosition).toBeNull();
      expect(doc.bookmarks).toEqual([]);
    });

    it('refuses an anonymous caller with 401, like every other scoped route', async () => {
      const { status, json } = await call('/api/account/export');
      expect(status).toBe(401);
      expect(json).toEqual({ ok: false, error: 'unauthorized' });
    });
  });

  describe('POST /api/account/data — delete my synced data', () => {
    it('empties all four tables and leaves the account working', async () => {
      const who = await populated();
      const before = await readAll(who);
      expect(before.reading).not.toBeNull();
      expect(before.bookmarks).toHaveLength(1);

      const purge = await call('/api/account/data', { method: 'POST', token: who });
      expect(purge.status).toBe(200);
      expect(purge.json).toEqual({ ok: true, purged: true });

      const after = await readAll(who);
      expect(after.reading).toBeNull();
      expect(after.preferences).toBeNull();
      expect(after.audioPosition).toBeNull();
      expect(after.bookmarks).toEqual([]);

      // ...and the ACCOUNT survives, which is the whole difference from deleting it. A write
      // still lands under the same session and reads back.
      const write = await call('/api/sync/reading-position', {
        method: 'PUT',
        token: who,
        body: position(9500, 7),
      });
      expect(write.status).toBe(200);
      expect((await readAll(who)).reading).toMatchObject({ userId: who.userId, surah: 7 });
    });

    it('is idempotent — a second purge succeeds and leaves nothing behind', async () => {
      // `db.batch()` of unconditional DELETEs, so a retried purge is a no-op rather than an
      // error. That matters because the client may well retry one it never saw the answer to.
      const who = await populated();
      expect((await call('/api/account/data', { method: 'POST', token: who })).status).toBe(200);
      const second = await call('/api/account/data', { method: 'POST', token: who });
      expect(second.status).toBe(200);
      expect(second.json).toEqual({ ok: true, purged: true });
      expect((await readAll(who)).bookmarks).toEqual([]);
    });

    it('destroys only the caller rows — a purge is not a truncate', async () => {
      // The failure this excludes is a purge whose predicate lost its `userId`, which would empty
      // the table for everybody and pass every single-user assertion above.
      const mine = await populated();
      const theirs = await populated();
      expect((await call('/api/account/data', { method: 'POST', token: mine })).status).toBe(200);
      const survived = await readAll(theirs);
      expect(survived.reading).toMatchObject({ userId: theirs.userId, surah: 3 });
      expect(survived.bookmarks).toHaveLength(1);
    });

    it('IS NEVER REFUSED BY THE WRITE CEILING — erasure is a right, not a budgeted action', async () => {
      // ⚠️ THIS CASE IS THE INVERSE OF THE ONE IT REPLACES, AND THE FIRST VERSION WAS WRONG. The
      // route checked the ceiling and answered 429, so a reader who had spent their daily writes
      // could not erase their data until the next UTC day — with no queued retry and no copy
      // telling them to come back. `lib/auth.ts` refuses to do exactly that on the deletion path
      // ("a cost guard standing in front of a legal right"); FR28 erasure is the same right.
      const who = await populated();
      await seedBudget(who.userId, DAILY_WRITE_CEILING);

      const purge = await call('/api/account/data', { method: 'POST', token: who });
      expect(purge.status).toBe(200);
      expect(purge.json).toEqual({ ok: true, purged: true });
      // ...and it really destroyed the rows, rather than answering 200 and doing nothing.
      const after = await readAll(who);
      expect(after.reading).toBeNull();
      expect(after.bookmarks).toEqual([]);

      // The ORDINARY write path is still refused at the ceiling — anti-vacuity for the case above,
      // and proof that the purge is an exception rather than the ceiling being broken.
      const write = await call('/api/sync/reading-position', {
        method: 'PUT',
        token: who,
        body: position(9600, 9),
      });
      expect(write.status).toBe(429);
    });

    it('still COSTS exactly one unit — accounted for, just never a veto', async () => {
      // Under the ceiling by one: the purge goes through and spends the last unit, so the next
      // ordinary write is refused. If the purge recorded one unit PER DESTROYED ROW, a reader who
      // purged four entities would be over by three — and if it recorded nothing, this write would
      // still be allowed.
      const who = await populated();
      await seedBudget(who.userId, DAILY_WRITE_CEILING - 1);
      expect((await call('/api/account/data', { method: 'POST', token: who })).status).toBe(200);

      const write = await call('/api/sync/reading-position', {
        method: 'PUT',
        token: who,
        body: position(9700, 11),
      });
      expect(write.status).toBe(429);
      expect(
        await countRows(`SELECT COUNT(*) FROM write_budget WHERE user_id = '${who.userId}'`)
      ).toBe(1);
    });

    it('refuses an anonymous caller with 401 and writes nothing', async () => {
      const { status, json } = await call('/api/account/data', { method: 'POST' });
      expect(status).toBe(401);
      expect(json).toEqual({ ok: false, error: 'unauthorized' });
    });

    it('REFUSES A CROSS-SITE ORIGIN, with a real session, and destroys nothing', async () => {
      // ⚠️ CSRF, AND THE COOKIE IS GENUINE — THAT IS THE SHAPE OF THE ATTACK. This route takes no
      // body, so a cross-site `fetch(url, {method:'POST', credentials:'include'})` is a CORS
      // SIMPLE request: no preflight fires, the middleware above only stops the attacker READING
      // the answer, and the erasure would already have happened. Upstream's `/delete-user` refuses
      // exactly this shape in the same worker.
      const who = await populated();

      const { status, json } = await call('/api/account/data', {
        method: 'POST',
        token: who,
        origin: 'https://evil.example',
      });

      expect(status).toBe(403);
      expect(json).toEqual({ ok: false, error: 'untrusted-origin' });
      // Counted in the table: a refusal that still purged would answer 403 just the same.
      expect(
        await countRows(`SELECT COUNT(*) FROM bookmarks WHERE user_id = '${who.userId}'`)
      ).toBeGreaterThan(0);
    });

    it('ACCEPTS the app scheme origin — anti-vacuity for the case above', async () => {
      // Native sends no `Origin` at all (every other case here proves that path); web and desktop
      // send one from `ALLOWED_ORIGINS`. The scheme origin is what `@better-auth/expo` promotes,
      // and refusing it would break the very client the check exists to keep working.
      const who = await populated();

      const { status } = await call('/api/account/data', {
        method: 'POST',
        token: who,
        origin: 'cloud-quran://',
      });

      expect(status).toBe(200);
      expect(
        await countRows(`SELECT COUNT(*) FROM bookmarks WHERE user_id = '${who.userId}'`)
      ).toBe(0);
    });
  });

  describe('POST /api/auth/delete-user — delete my account', () => {
    /** Better Auth's own route. There is deliberately no route of ours; the 501 stub was deleted. */
    async function deleteAccount(who: Identity) {
      const res = await fetch(`${baseUrl}/api/auth/delete-user`, {
        method: 'POST',
        headers: {
          'content-type': 'application/json',
          'cf-connecting-ip': nextCallerIp(),
          cookie: who.cookie,
          origin: 'cloud-quran://',
        },
        body: '{}',
      });
      return { status: res.status, json: (await res.json()) as Record<string, unknown> };
    }

    it('takes the synced rows, the identity rows AND the write-budget row', async () => {
      const who = await populated();
      // Give them a counter row to leave behind, which is exactly what the 'account' purge scope
      // exists to prevent: there is no foreign key from write_budget to user, so a row left here
      // is owned by nobody and billed forever.
      await seedBudget(who.userId, 5);

      const deleted = await deleteAccount(who);
      expect(deleted.status).toBe(200);
      expect(deleted.json).toMatchObject({ success: true });

      // ⚠️ COUNTED IN THE TABLES, NOT THROUGH THE API. After a deletion there is no session left
      // to ask "did anything stay behind on me" — orphaned rows are invisible to every route and
      // permanent. The same argument the merge tests make, applied to the terminal case.
      const id = who.userId;
      expect(await countRows(`SELECT COUNT(*) FROM user WHERE id = '${id}'`)).toBe(0);
      expect(await countRows(`SELECT COUNT(*) FROM session WHERE user_id = '${id}'`)).toBe(0);
      expect(await countRows(`SELECT COUNT(*) FROM bookmarks WHERE user_id = '${id}'`)).toBe(0);
      expect(
        await countRows(`SELECT COUNT(*) FROM reading_positions WHERE user_id = '${id}'`)
      ).toBe(0);
      expect(await countRows(`SELECT COUNT(*) FROM preferences WHERE user_id = '${id}'`)).toBe(0);
      expect(await countRows(`SELECT COUNT(*) FROM audio_positions WHERE user_id = '${id}'`)).toBe(
        0
      );
      expect(await countRows(`SELECT COUNT(*) FROM write_budget WHERE user_id = '${id}'`)).toBe(0);
    });

    it('leaves the session dead — the cookie no longer resolves an identity', async () => {
      const who = await populated();
      expect((await deleteAccount(who)).status).toBe(200);
      const after = await call('/api/sync/reading-position', { token: who });
      expect(after.status).toBe(401);
    });

    it('works on a session far older than any freshness window', async () => {
      // ⚠️ THE CASE `session.freshAge` WOULD BREAK. Upstream refuses `/delete-user` without a
      // password when the session is older than `freshAge` (default 24h) — and this app has no
      // password on ANY account, so the default would make in-app deletion impossible for anyone
      // signed in longer than a day, which Apple 5.1.1(v) forbids. Backdating the session row is
      // the only way to reach that branch inside one test run; with `freshAge: 0` it must still
      // delete. Restoring the default reddens exactly this case.
      const who = await populated();
      const longAgo = Date.now() - 400 * 24 * 60 * 60 * 1000;
      await seed(`UPDATE session SET created_at = ${longAgo} WHERE user_id = '${who.userId}'`);
      expect((await deleteAccount(who)).status).toBe(200);
      expect(await countRows(`SELECT COUNT(*) FROM user WHERE id = '${who.userId}'`)).toBe(0);
    });

    it('refuses an anonymous caller — no session, no deletion', async () => {
      const res = await fetch(`${baseUrl}/api/auth/delete-user`, {
        method: 'POST',
        headers: { 'content-type': 'application/json', 'cf-connecting-ip': nextCallerIp() },
        body: '{}',
      });
      expect(res.status).toBe(401);
    });

    it('the 501 POST /api/account/delete stub is GONE, not merely unused', async () => {
      // One door onto deletion. A second one that answers 501 is a route a later story fills in
      // by accident — the `linkSocial` lesson, which cost this project a production defect.
      const who = await identity();
      const { status, json } = await call('/api/account/delete', { method: 'POST', token: who });
      expect(status).toBe(404);
      expect(json).toEqual({ ok: false, error: 'not-found' });
    });
  });

  /**
   * ⚠️ THE WINDOW THIS SUITE STRUCTURALLY COULD NOT SEE UNTIL IT CARRIED THE COOKIE CACHE.
   *
   * `identity()` at the top of this file keeps only the FIRST cookie of the sign-in response — the
   * session token — and throws `better-auth.session_data` away. So every case above has always
   * resolved through a database read, which is exactly why a green suite shipped this defect.
   *
   * Measured against the PRODUCTION worker and real D1 on 2026-08-26, in this order:
   * `/delete-user` answered `{"success":true}` · `GET /api/auth/get-session` still returned the
   * session · `GET /api/sync/bookmarks` answered 200 · `POST /api/sync/bookmarks` SUCCEEDED,
   * creating a row whose `userId` names a user that no longer exists. That row is invisible to
   * every route in this worker, uncollectable, and billed forever — the precise orphan the
   * `beforeDelete` hook exists to prevent, walking back in through the front door.
   *
   * The two halves below are the two halves of the fix, and the read is what stops the write
   * assertion from passing vacuously: the cached identity is demonstrably STILL RESOLVING at the
   * moment the write is refused. A read on a deleted user costs nothing — their rows are already
   * gone — and that staleness is what pays for `session.cookieCache`.
   */
  describe('the cookie-cache window — a deleted user may still read, but may NEVER write', () => {
    /**
     * Every cookie a response sets, as `name=value` pairs. Expiring entries (an empty value) are
     * dropped, so a jar never carries a cookie the server just cleared.
     *
     * ⚠️ `getSetCookie()` IS CAST IN, AND IT HAS TO BE. This file typechecks against
     * `@cloudflare/workers-types`, whose `Headers` offers `getAll()` and no `getSetCookie()`;
     * the suite RUNS on Node, whose `Headers` is undici's and offers the exact opposite. Calling
     * the typed one would compile and then crash. Splitting `get('set-cookie')` is not the way
     * out either — undici joins the headers with a comma, and a cookie's `Expires` attribute
     * contains one.
     */
    function jarFrom(res: Response): string[] {
      const setCookies = (res.headers as unknown as { getSetCookie(): string[] }).getSetCookie();
      return setCookies
        .map((entry) => entry.split(';')[0])
        .filter((pair) => (pair.split('=')[1] ?? '').length > 0);
    }

    /**
     * Warm the cookie cache for an existing session and hand back a jar that CARRIES it.
     *
     * `GET /api/auth/get-session` re-issues `better-auth.session_data` on every database read
     * (upstream's `setCookieCache`), so this needs no test-only door — it is one of the calls the
     * app itself makes.
     */
    async function withCookieCache(who: Identity): Promise<Identity> {
      const res = await fetch(`${baseUrl}/api/auth/get-session`, {
        headers: { cookie: who.cookie, 'cf-connecting-ip': nextCallerIp() },
      });
      expect(res.status).toBe(200);
      const cookies = jarFrom(res);
      // Anti-vacuity, and the whole reason this describe exists: without this cookie the case
      // below degenerates into the one three blocks up, which already passed WITH the bug.
      expect(cookies.some((pair) => pair.startsWith('better-auth.session_data'))).toBe(true);
      return { ...who, cookie: [who.cookie, ...cookies].join('; ') };
    }

    it('refuses every write on a cached session whose user is gone, and creates no row', async () => {
      const who = await withCookieCache(await populated());
      const id = who.userId;

      const res = await fetch(`${baseUrl}/api/auth/delete-user`, {
        method: 'POST',
        headers: {
          'content-type': 'application/json',
          'cf-connecting-ip': nextCallerIp(),
          cookie: who.cookie,
          origin: 'cloud-quran://',
        },
        body: '{}',
      });
      expect(res.status).toBe(200);
      expect(await countRows(`SELECT COUNT(*) FROM user WHERE id = '${id}'`)).toBe(0);

      // The cache is still live — this is the 200 that was measured in production, and it is the
      // accepted cost of keeping the cookie cache on the read path.
      const read = await call('/api/sync/bookmarks', { token: who });
      expect(read.status).toBe(200);

      // ⚠️ THE EXPORT IS THE ONE READ THAT DOES **NOT** GET THAT CONCESSION, AND NOTHING OBSERVED
      // IT UNTIL NOW. `app.ts` calls plain `identify(c)` there rather than `identify(c, readOnly)`
      // — a one-token difference that reads as an inconsistency with the four GETs above it, and
      // whose removal left the whole suite green. What it buys: the four sync GETs hand back rows
      // a departed user no longer has, while THIS one emits their complete personal-data document,
      // so a session revoked on another device could extract the lot for fifteen minutes.
      const exported = await call('/api/account/export', { token: who });
      expect(exported.status).toBe(401);
      expect(exported.json).toEqual({ ok: false, error: 'unauthorized' });

      // ...and every write path refuses it anyway. All four are asserted because they resolve
      // identity through three different call sites: `runWrite`, and the two bookmark routes.
      const created = await call('/api/sync/bookmarks', {
        method: 'POST',
        token: who,
        body: { id: `orphan-${id}`, surah: 2, verse: 255, label: 'Al Baqarah', createdAt: 9900 },
      });
      expect(created.status).toBe(401);
      expect(created.json).toEqual({ ok: false, error: 'unauthorized' });

      for (const [path, method, body] of [
        ['/api/sync/reading-position', 'PUT', position(9900, 12)],
        ['/api/sync/bookmarks/bm-' + id, 'DELETE', undefined],
        ['/api/account/data', 'POST', undefined],
      ] as const) {
        const refused = await call(path, { method, token: who, body });
        expect(refused.status, `${method} ${path}`).toBe(401);
      }

      // ⚠️ COUNTED IN THE TABLE, NOT THROUGH THE API. A row on a departed user is unreachable by
      // every route here, so a 401 alone would not prove nothing was written.
      expect(await countRows(`SELECT COUNT(*) FROM bookmarks WHERE user_id = '${id}'`)).toBe(0);
      expect(
        await countRows(`SELECT COUNT(*) FROM reading_positions WHERE user_id = '${id}'`)
      ).toBe(0);
    });
  });
});
