/**
 * The gradle-heap config plugin (Story 20.8, Step G).
 *
 * The property under test is that the plugin OWNS the value: `gradle.properties` is regenerated by
 * every prebuild from the RN template, which ships its own `org.gradle.jvmargs=-Xmx2048m`. A plugin
 * that merely appends would leave two entries and let Gradle read whichever it likes — so the
 * replace-not-append behaviour is the whole point, not a detail.
 */

// The plugin is CommonJS because Expo's config resolution requires it directly.
const { setJvmArgs, JVM_ARGS } = require('./with-gradle-heap');

type GradleProp =
  | { type: 'property'; key: string; value: string }
  | { type: 'comment'; value: string }
  | { type: 'empty' };

const asProperties = (items: GradleProp[]) =>
  items.filter((i): i is Extract<GradleProp, { type: 'property' }> => i.type === 'property');

describe('with-gradle-heap', () => {
  it('REPLACES the template default rather than appending a second jvmargs entry', () => {
    const template: GradleProp[] = [
      { type: 'comment', value: 'Project-wide Gradle settings.' },
      { type: 'property', key: 'org.gradle.jvmargs', value: '-Xmx2048m -XX:MaxMetaspaceSize=512m' },
      { type: 'property', key: 'android.useAndroidX', value: 'true' },
    ];

    const jvmargs = asProperties(setJvmArgs(template)).filter(
      (p) => p.key === 'org.gradle.jvmargs'
    );

    expect(jvmargs).toHaveLength(1);
    expect(jvmargs[0].value).toBe(JVM_ARGS);
  });

  it('adds the entry when the template has none', () => {
    const result = asProperties(setJvmArgs([{ type: 'property', key: 'a', value: 'b' }]));
    expect(result.find((p) => p.key === 'org.gradle.jvmargs')?.value).toBe(JVM_ARGS);
  });

  it('preserves every unrelated property', () => {
    const template: GradleProp[] = [
      { type: 'property', key: 'android.useAndroidX', value: 'true' },
      { type: 'property', key: 'org.gradle.jvmargs', value: '-Xmx2048m' },
      { type: 'property', key: 'newArchEnabled', value: 'true' },
    ];

    const keys = asProperties(setJvmArgs(template)).map((p) => p.key);
    expect(keys).toEqual(expect.arrayContaining(['android.useAndroidX', 'newArchEnabled']));
  });

  it('leaves a comment at the property explaining why the file must not be hand-edited', () => {
    const comments: GradleProp[] = setJvmArgs([]).filter((i: GradleProp) => i.type === 'comment');
    expect(
      comments.some((c: GradleProp) => 'value' in c && /gitignored|prebuild/i.test(c.value))
    ).toBe(true);
  });

  it('is IDEMPOTENT — a prebuild without --clean re-runs it over its own output', () => {
    // `expo prebuild` (no --clean) parses the EXISTING gradle.properties into modResults, so the
    // plugin runs over what it wrote last time. Filtering only the property left the comment to
    // accumulate one copy per prebuild — observable in `expo config --type introspect`, which
    // emitted the marker comment twice on the real tree before this was fixed.
    const once = setJvmArgs([
      { type: 'property', key: 'org.gradle.jvmargs', value: '-Xmx2048m' },
      { type: 'property', key: 'android.useAndroidX', value: 'true' },
    ]);
    const thrice = setJvmArgs(setJvmArgs(setJvmArgs(once)));

    expect(thrice).toEqual(once);

    const count = (items: GradleProp[], pred: (i: GradleProp) => boolean) =>
      items.filter(pred).length;
    expect(
      count(thrice, (i) => i.type === 'comment' && i.value.includes('with-gradle-heap.js'))
    ).toBe(1);
    expect(count(thrice, (i) => i.type === 'property' && i.key === 'org.gradle.jvmargs')).toBe(1);
    expect(count(thrice, (i) => i.type === 'property' && i.key === 'android.useAndroidX')).toBe(1);
  });

  it('raises the heap above the template default that OOMs in dex merging', () => {
    const heap = /-Xmx(\d+)m/.exec(JVM_ARGS);
    expect(heap).not.toBeNull();
    expect(Number(heap?.[1])).toBeGreaterThan(2048);
  });
});
