"""Split QUL font 458's COLR v0 bands into themeable monochrome layers.

Requires fontTools. Sources are the authenticated QUL cache; outputs are bundled assets.
Run: python3 scripts/build-surah-header-fonts.py
The white COLR backing is omitted so the reader's page colour shows through.
"""
from copy import deepcopy
from pathlib import Path
import bz2
import json
from fontTools.ttLib import TTFont
from fontTools.pens.ttGlyphPen import TTGlyphPen

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / 'build/qul-cache/font/header/QCF_SurahHeader_COLOR-Regular.ttf'
DEST = ROOT / 'apps/expo/assets/fonts/surah-header'
DEST.mkdir(parents=True, exist_ok=True)
mapping = json.loads(bz2.open(ROOT / 'build/qul-cache/font/header-lig.dl').read())
source_glyphs = [mapping[f'surah-{number}'].strip() for number in range(1, 115)]
# Presentation-form codepoints are decomposed by browser Arabic shaping before lookup.
# Private-use aliases preserve the ornament as one glyph on native and web.
glyphs = [chr(0xE001 + index) for index in range(114)]

for family, colours in [('CloudQuranSurahLine', {13, 19}), ('CloudQuranSurahAccent', {10, 11, 16})]:
    font = TTFont(SOURCE, recalcTimestamp=False)
    order = list(font.getGlyphOrder())
    for name, layers in font['COLR'].ColorLayers.items():
        base = name + '.original'
        font['glyf'][base] = deepcopy(font['glyf'][name])
        font['hmtx'][base] = font['hmtx'][name]
        order.append(base)
        pen = TTGlyphPen(font['glyf'])
        for layer in layers:
            if layer.colorID in colours:
                pen.addComponent(base if layer.name == name else layer.name, (1, 0, 0, 1, 0, 0))
        font['glyf'][name] = pen.glyph()
        font['hmtx'][name] = (font['hmtx'][name][0], 0)
    font.setGlyphOrder(order)
    cmap = font.getBestCmap()
    aliases = {ord(alias): cmap[ord(source)] for source, alias in zip(source_glyphs, glyphs)}
    for table in font['cmap'].tables:
        if table.isUnicode():
            table.cmap.update(aliases)
    for table in ['COLR', 'CPAL']:
        del font[table]
    for record in font['name'].names:
        if record.nameID in (1, 4, 6, 16):
            record.string = family.encode(record.getEncoding())
        elif record.nameID in (2, 17):
            record.string = 'Regular'.encode(record.getEncoding())
    font.save(DEST / f'{family}.ttf')

# Preserve the encoded glyphs. No Arabic normalization applies to these codepoints.
(ROOT / 'apps/expo/src/constants/surah-header.ts').write_text(
    '/** QUL font 458 ligatures, in surah order. Generated by scripts/build-surah-header-fonts.py. */\n'
    + 'export const SURAH_HEADER_GLYPHS: readonly string[] = '
    + json.dumps(glyphs, ensure_ascii=True, indent=2) + ';\n'
    + 'export const SURAH_HEADER_FONTS = {\n'
    + "  CloudQuranSurahLine: require('../../assets/fonts/surah-header/CloudQuranSurahLine.ttf'),\n"
    + "  CloudQuranSurahAccent: require('../../assets/fonts/surah-header/CloudQuranSurahAccent.ttf'),\n"
    + '};\n'
)
print('Built two monochrome bands and all 114 ligatures.')
