// Generates verse-page-map.ts from mushaf-layout JSON files
// Run: bun run scripts/generate-verse-page-map.ts

import { readdirSync, readFileSync, writeFileSync } from 'fs';
import { resolve } from 'path';

import type { MushafPageLayout } from '../packages/quran-data/src/mushaf-layout';

const ROOT = resolve(import.meta.dir, '..');
const LAYOUT_DIR = resolve(ROOT, 'packages/quran-data/data/mushaf-layout');
const OUTPUT_PATH = resolve(ROOT, 'packages/quran-data/src/verse-page-map.ts');

function main() {
  console.log('=== Generating Verse-Page Map ===\n');

  // Read all layout JSON files
  const files = readdirSync(LAYOUT_DIR)
    .filter((f) => f.endsWith('.json'))
    .sort();

  console.log(`Found ${files.length} layout files`);

  if (files.length !== 604) {
    throw new Error(`Expected 604 layout files, found ${files.length}`);
  }

  // Build verse → page map
  // Key: "surah:verse" → page number
  const versePageMap = new Map<string, number>();

  // Build page → first verse map
  // Key: page number → { surah, verse }
  const pageFirstVerse = new Map<number, { surah: number; verse: number }>();

  for (const file of files) {
    const raw = JSON.parse(readFileSync(resolve(LAYOUT_DIR, file), 'utf-8')) as MushafPageLayout;
    const layout = raw;
    const pageNum = layout.page;

    let firstVerseOnPage: { surah: number; verse: number } | null = null;

    for (const line of layout.lines) {
      if (line.type !== 'text' || !line.words) continue;

      for (const word of line.words) {
        const parts = word.location.split(':');
        const surah = parseInt(parts[0], 10);
        const verse = parseInt(parts[1], 10);
        const key = `${surah}:${verse}`;

        // Only set if not already mapped (first occurrence = correct page)
        if (!versePageMap.has(key)) {
          versePageMap.set(key, pageNum);
        }

        // Track first verse on this page
        if (!firstVerseOnPage) {
          firstVerseOnPage = { surah, verse };
        }
      }
    }

    if (firstVerseOnPage) {
      pageFirstVerse.set(pageNum, firstVerseOnPage);
    }
  }

  console.log(`Mapped ${versePageMap.size} verses across 604 pages`);

  // Validate completeness
  if (versePageMap.size !== 6236) {
    console.warn(`Warning: Expected 6236 verse mappings, got ${versePageMap.size}`);
  }

  // Generate TypeScript output
  const lines: string[] = [];
  lines.push('// Auto-generated by scripts/generate-verse-page-map.ts — DO NOT EDIT');
  lines.push('// Maps each Quran verse to its mushaf page number (1-604)');
  lines.push('');
  lines.push("import { TOTAL_PAGES } from './constants';");
  lines.push('');

  // Generate VERSE_PAGE_MAP as a Record
  lines.push('/** Verse key "surah:verse" → mushaf page number (1-604) */');
  lines.push('export const VERSE_PAGE_MAP: Record<string, number> = {');
  // Sort entries by surah then verse
  const sortedEntries = [...versePageMap.entries()].sort((a, b) => {
    const [as, av] = a[0].split(':').map(Number);
    const [bs, bv] = b[0].split(':').map(Number);
    return as !== bs ? as - bs : av - bv;
  });
  for (const [key, page] of sortedEntries) {
    lines.push(`  '${key}': ${page},`);
  }
  lines.push('};');
  lines.push('');

  // Generate PAGE_FIRST_VERSE as an array (index 0 = page 1)
  lines.push('/** First verse on each page. Index 0 = page 1, index 603 = page 604 */');
  lines.push('export const PAGE_FIRST_VERSE: ReadonlyArray<{ surah: number; verse: number }> = [');
  for (let p = 1; p <= 604; p++) {
    const fv = pageFirstVerse.get(p);
    if (fv) {
      lines.push(`  { surah: ${fv.surah}, verse: ${fv.verse} },`);
    } else {
      // Page with no text (shouldn't happen, but handle gracefully)
      lines.push('  { surah: 0, verse: 0 },');
    }
  }
  lines.push('];');
  lines.push('');

  // Generate lookup functions
  lines.push('/**');
  lines.push(' * Get the mushaf page number for a given verse.');
  lines.push(' * @returns Page number (1-604), or -1 if not found');
  lines.push(' */');
  lines.push('export function getPageForVerse(surah: number, verse: number): number {');
  // biome-ignore lint/suspicious/noTemplateCurlyInString: code generation — template literal is output, not a mistake
  lines.push('  return VERSE_PAGE_MAP[`${surah}:${verse}`] ?? -1;');
  lines.push('}');
  lines.push('');

  lines.push('/**');
  lines.push(' * Get the first verse on a given mushaf page.');
  lines.push(' * @returns { surah, verse } or { surah: 0, verse: 0 } if invalid page');
  lines.push(' */');
  lines.push(
    'export function getFirstVerseForPage(page: number): { surah: number; verse: number } {',
  );
  lines.push('  if (page < 1 || page > TOTAL_PAGES) {');
  lines.push('    return { surah: 0, verse: 0 };');
  lines.push('  }');
  lines.push('  return PAGE_FIRST_VERSE[page - 1];');
  lines.push('}');
  lines.push('');

  const output = lines.join('\n');
  writeFileSync(OUTPUT_PATH, output, 'utf-8');

  console.log(`\n✅ Generated: ${OUTPUT_PATH}`);
  console.log(`   Verse mappings: ${versePageMap.size}`);
  console.log(`   Page entries: ${pageFirstVerse.size}`);
}

main().catch((err) => {
  console.error('❌ Generation failed:', err);
  process.exit(1);
});
