import { Database } from 'bun:sqlite';
import { existsSync, writeFileSync } from 'fs';
import { resolve } from 'path';

const ROOT = resolve(import.meta.dir, '..');
const DB_PATH = resolve(ROOT, 'apps/expo/src/data/quran.db');
const HASHES_PATH = resolve(ROOT, 'packages/quran-data/src/hashes.ts');

interface VerseRow {
  surah_number: number;
  verse_number: number;
  uthmani_text: string;
}

function hashAyah(surah: number, verse: number, text: string): string {
  const hasher = new Bun.CryptoHasher('sha256');
  hasher.update(`${surah}:${verse}:${text}`);
  return hasher.digest('hex');
}

function generateHashes(db: Database): Record<string, string> {
  const verses = db
    .query(
      'SELECT surah_number, verse_number, uthmani_text FROM verses ORDER BY surah_number, verse_number',
    )
    .all() as VerseRow[];
  const hashes: Record<string, string> = {};

  for (const verse of verses) {
    const key = `${verse.surah_number}:${verse.verse_number}`;
    hashes[key] = hashAyah(verse.surah_number, verse.verse_number, verse.uthmani_text);
  }

  return hashes;
}

function writeHashesFile(hashes: Record<string, string>): void {
  const entries = Object.entries(hashes)
    .map(([key, hash]) => `  '${key}': '${hash}',`)
    .join('\n');

  const content = `// Auto-generated by scripts/verify-quran.ts — DO NOT EDIT
// SHA-256 hashes of Quran verse text for integrity verification
// Format: 'surah:verse' → SHA-256(surah:verse:uthmani_text)

export const VERSE_HASHES: Record<string, string> = {
${entries}
};
`;

  writeFileSync(HASHES_PATH, content, 'utf-8');
}

async function main() {
  console.log('=== Quran Integrity Verification ===\n');

  if (!existsSync(DB_PATH)) {
    console.error('❌ Database not found at:', DB_PATH);
    console.error('   Run "bun run prepare-data" first.');
    process.exit(1);
  }

  const db = new Database(DB_PATH, { readonly: true });

  // Generate current hashes from database
  console.log('Computing SHA-256 hashes for all verses...');
  const currentHashes = generateHashes(db);
  const totalVerses = Object.keys(currentHashes).length;
  console.log(`  Computed hashes for ${totalVerses} verses`);

  db.close();

  // Check if stored hashes exist
  if (!existsSync(HASHES_PATH)) {
    // First run: generate and save hashes
    console.log('\nFirst run — generating hashes file...');
    writeHashesFile(currentHashes);
    console.log(`  Written to: ${HASHES_PATH}`);
    console.log(`\n✅ Verification PASSED (initial hash generation)`);
    console.log(`   Total verses checked: ${totalVerses}`);
    process.exit(0);
  }

  // Subsequent runs: compare against stored hashes
  console.log('\nComparing against stored hashes...');
  const storedModule = await import(HASHES_PATH);
  if (!storedModule.VERSE_HASHES || typeof storedModule.VERSE_HASHES !== 'object') {
    throw new Error(`Invalid hashes file: VERSE_HASHES export not found in ${HASHES_PATH}`);
  }
  const storedHashes: Record<string, string> = storedModule.VERSE_HASHES;

  const mismatches: string[] = [];
  const missing: string[] = [];
  const extra: string[] = [];

  // Check all current hashes against stored
  for (const [key, hash] of Object.entries(currentHashes)) {
    if (!(key in storedHashes)) {
      extra.push(key);
    } else if (storedHashes[key] !== hash) {
      mismatches.push(key);
    }
  }

  // Check for stored hashes not in current
  for (const key of Object.keys(storedHashes)) {
    if (!(key in currentHashes)) {
      missing.push(key);
    }
  }

  if (mismatches.length === 0 && missing.length === 0 && extra.length === 0) {
    console.log(`\n✅ Verification PASSED`);
    console.log(`   Total verses checked: ${totalVerses}`);
    console.log(`   All hashes match stored values`);
    process.exit(0);
  }

  // Report failures
  console.error(`\n❌ Verification FAILED`);
  console.error(`   Total verses checked: ${totalVerses}`);

  if (mismatches.length > 0) {
    console.error(`\n   ${mismatches.length} hash mismatches:`);
    for (const key of mismatches) {
      console.error(`     ${key}: expected ${storedHashes[key]}, got ${currentHashes[key]}`);
    }
  }

  if (missing.length > 0) {
    console.error(`\n   ${missing.length} verses missing from database:`);
    for (const key of missing) {
      console.error(`     ${key}`);
    }
  }

  if (extra.length > 0) {
    console.error(`\n   ${extra.length} extra verses in database:`);
    for (const key of extra) {
      console.error(`     ${key}`);
    }
  }

  process.exit(1);
}

main().catch((err) => {
  console.error('❌ Verification failed:', err);
  process.exit(1);
});
