// Auto-generated by scripts/verify-artifacts.ts — DO NOT EDIT
// SHA-256 over the generated Quran artifacts the per-ayah gate does not cover.
// Each entry is one artifact: a canonical, ORDERED serialization hashed whole, plus the row
// count it was minted from (a digest cannot see truncation; the count can).

export interface ArtifactDigest {
  digest: string;
  rows: number;
}

export const ARTIFACT_DIGESTS: Record<string, ArtifactDigest> = {
  'verses.simple_text': {
    digest: 'aafe11198c9d4c44e010cdd5ad281a68c68f2d5ca397abf69d04985a03547383',
    rows: 6236,
  },
  translations: {
    digest: 'ab756b138e2f7a860bd734ee6eb7f375a4bb63643b57e4fae635b4e15c8b322e',
    rows: 6236,
  },
  surah_metadata: {
    digest: '9b33522ccd8dfed9d5798113021f2e1bb2326d4ca454e26f9b535b30dc98afe0',
    rows: 114,
  },
  'mushaf-layout': {
    digest: '0a28ac5e498974861b889004dea40c2ed8cfbf0a3d5f2a3d69f8e4db4dc61093',
    rows: 604,
  },
  'verse-page-map': {
    digest: 'bdf2c5ab8d039251af8ab4fbf748ad1beb903a5a42c6574379a2488cf8b8ce54',
    rows: 1,
  },
};
