// Auto-generated by scripts/prepare-data.ts — DO NOT EDIT
// What apps/expo/src/data/quran.db's bundled translation was built from (story 8-4). The app
// renders `attribution` beside the text; `pnpm verify` checks `sourceVersion` against the
// ledger's pin for `sourceKey` (packages/quran-data/data/packs/LICENCES.md, "quranenc-bundled-english").

export interface BundledTranslationRecord {
  licenceId: string;
  source: string;
  sourceKey: string;
  sourceVersion: string;
  language: string;
  direction: 'ltr' | 'rtl';
  title: string;
  attribution: string;
}

export const BUNDLED_TRANSLATION: BundledTranslationRecord = {
  licenceId: 'quranenc-bundled-english',
  source: 'QuranEnc',
  sourceKey: 'english_rwwad',
  sourceVersion: '1.0.19',
  language: 'en',
  direction: 'ltr',
  title: 'English Translation - Rowwad Translation Center',
  attribution: 'English Translation - Rowwad Translation Center · QuranEnc.com · v1.0.19',
};
