import type { Surah } from './types';

export type SurahMetadata = Surah;

export const SURAH_METADATA: SurahMetadata[] = [
  {
    number: 1,
    nameArabic: 'الفاتحة',
    nameEnglish: 'The Opening',
    nameTransliteration: 'Al-Fatihah',
    verseCount: 7,
    revelationType: 'meccan',
    order: 5,
  },
  {
    number: 2,
    nameArabic: 'البقرة',
    nameEnglish: 'The Cow',
    nameTransliteration: 'Al-Baqarah',
    verseCount: 286,
    revelationType: 'medinan',
    order: 87,
  },
  {
    number: 3,
    nameArabic: 'آل عمران',
    nameEnglish: 'Family of Imran',
    nameTransliteration: 'Ali-Imran',
    verseCount: 200,
    revelationType: 'medinan',
    order: 89,
  },
  {
    number: 4,
    nameArabic: 'النساء',
    nameEnglish: 'The Women',
    nameTransliteration: 'An-Nisa',
    verseCount: 176,
    revelationType: 'medinan',
    order: 92,
  },
  {
    number: 5,
    nameArabic: 'المائدة',
    nameEnglish: 'The Table Spread',
    nameTransliteration: "Al-Ma'idah",
    verseCount: 120,
    revelationType: 'medinan',
    order: 112,
  },
  {
    number: 6,
    nameArabic: 'الأنعام',
    nameEnglish: 'The Cattle',
    nameTransliteration: "Al-An'am",
    verseCount: 165,
    revelationType: 'meccan',
    order: 55,
  },
  {
    number: 7,
    nameArabic: 'الأعراف',
    nameEnglish: 'The Heights',
    nameTransliteration: "Al-A'raf",
    verseCount: 206,
    revelationType: 'meccan',
    order: 39,
  },
  {
    number: 8,
    nameArabic: 'الأنفال',
    nameEnglish: 'The Spoils of War',
    nameTransliteration: 'Al-Anfal',
    verseCount: 75,
    revelationType: 'medinan',
    order: 88,
  },
  {
    number: 9,
    nameArabic: 'التوبة',
    nameEnglish: 'The Repentance',
    nameTransliteration: 'At-Tawbah',
    verseCount: 129,
    revelationType: 'medinan',
    order: 113,
  },
  {
    number: 10,
    nameArabic: 'يونس',
    nameEnglish: 'Jonah',
    nameTransliteration: 'Yunus',
    verseCount: 109,
    revelationType: 'meccan',
    order: 51,
  },
  {
    number: 11,
    nameArabic: 'هود',
    nameEnglish: 'Hud',
    nameTransliteration: 'Hud',
    verseCount: 123,
    revelationType: 'meccan',
    order: 52,
  },
  {
    number: 12,
    nameArabic: 'يوسف',
    nameEnglish: 'Joseph',
    nameTransliteration: 'Yusuf',
    verseCount: 111,
    revelationType: 'meccan',
    order: 53,
  },
  {
    number: 13,
    nameArabic: 'الرعد',
    nameEnglish: 'The Thunder',
    nameTransliteration: "Ar-Ra'd",
    verseCount: 43,
    revelationType: 'medinan',
    order: 96,
  },
  {
    number: 14,
    nameArabic: 'ابراهيم',
    nameEnglish: 'Abraham',
    nameTransliteration: 'Ibrahim',
    verseCount: 52,
    revelationType: 'meccan',
    order: 72,
  },
  {
    number: 15,
    nameArabic: 'الحجر',
    nameEnglish: 'The Rocky Tract',
    nameTransliteration: 'Al-Hijr',
    verseCount: 99,
    revelationType: 'meccan',
    order: 54,
  },
  {
    number: 16,
    nameArabic: 'النحل',
    nameEnglish: 'The Bee',
    nameTransliteration: 'An-Nahl',
    verseCount: 128,
    revelationType: 'meccan',
    order: 70,
  },
  {
    number: 17,
    nameArabic: 'الإسراء',
    nameEnglish: 'The Night Journey',
    nameTransliteration: 'Al-Isra',
    verseCount: 111,
    revelationType: 'meccan',
    order: 50,
  },
  {
    number: 18,
    nameArabic: 'الكهف',
    nameEnglish: 'The Cave',
    nameTransliteration: 'Al-Kahf',
    verseCount: 110,
    revelationType: 'meccan',
    order: 69,
  },
  {
    number: 19,
    nameArabic: 'مريم',
    nameEnglish: 'Mary',
    nameTransliteration: 'Maryam',
    verseCount: 98,
    revelationType: 'meccan',
    order: 44,
  },
  {
    number: 20,
    nameArabic: 'طه',
    nameEnglish: 'Ta-Ha',
    nameTransliteration: 'Ta-Ha',
    verseCount: 135,
    revelationType: 'meccan',
    order: 45,
  },
  {
    number: 21,
    nameArabic: 'الأنبياء',
    nameEnglish: 'The Prophets',
    nameTransliteration: 'Al-Anbiya',
    verseCount: 112,
    revelationType: 'meccan',
    order: 73,
  },
  {
    number: 22,
    nameArabic: 'الحج',
    nameEnglish: 'The Pilgrimage',
    nameTransliteration: 'Al-Hajj',
    verseCount: 78,
    revelationType: 'medinan',
    order: 103,
  },
  {
    number: 23,
    nameArabic: 'المؤمنون',
    nameEnglish: 'The Believers',
    nameTransliteration: "Al-Mu'minun",
    verseCount: 118,
    revelationType: 'meccan',
    order: 74,
  },
  {
    number: 24,
    nameArabic: 'النور',
    nameEnglish: 'The Light',
    nameTransliteration: 'An-Nur',
    verseCount: 64,
    revelationType: 'medinan',
    order: 102,
  },
  {
    number: 25,
    nameArabic: 'الفرقان',
    nameEnglish: 'The Criterion',
    nameTransliteration: 'Al-Furqan',
    verseCount: 77,
    revelationType: 'meccan',
    order: 42,
  },
  {
    number: 26,
    nameArabic: 'الشعراء',
    nameEnglish: 'The Poets',
    nameTransliteration: "Ash-Shu'ara",
    verseCount: 227,
    revelationType: 'meccan',
    order: 47,
  },
  {
    number: 27,
    nameArabic: 'النمل',
    nameEnglish: 'The Ant',
    nameTransliteration: 'An-Naml',
    verseCount: 93,
    revelationType: 'meccan',
    order: 48,
  },
  {
    number: 28,
    nameArabic: 'القصص',
    nameEnglish: 'The Stories',
    nameTransliteration: 'Al-Qasas',
    verseCount: 88,
    revelationType: 'meccan',
    order: 49,
  },
  {
    number: 29,
    nameArabic: 'العنكبوت',
    nameEnglish: 'The Spider',
    nameTransliteration: 'Al-Ankabut',
    verseCount: 69,
    revelationType: 'meccan',
    order: 85,
  },
  {
    number: 30,
    nameArabic: 'الروم',
    nameEnglish: 'The Romans',
    nameTransliteration: 'Ar-Rum',
    verseCount: 60,
    revelationType: 'meccan',
    order: 84,
  },
  {
    number: 31,
    nameArabic: 'لقمان',
    nameEnglish: 'Luqman',
    nameTransliteration: 'Luqman',
    verseCount: 34,
    revelationType: 'meccan',
    order: 57,
  },
  {
    number: 32,
    nameArabic: 'السجدة',
    nameEnglish: 'The Prostration',
    nameTransliteration: 'As-Sajdah',
    verseCount: 30,
    revelationType: 'meccan',
    order: 75,
  },
  {
    number: 33,
    nameArabic: 'الأحزاب',
    nameEnglish: 'The Combined Forces',
    nameTransliteration: 'Al-Ahzab',
    verseCount: 73,
    revelationType: 'medinan',
    order: 90,
  },
  {
    number: 34,
    nameArabic: 'سبإ',
    nameEnglish: 'Sheba',
    nameTransliteration: 'Saba',
    verseCount: 54,
    revelationType: 'meccan',
    order: 58,
  },
  {
    number: 35,
    nameArabic: 'فاطر',
    nameEnglish: 'Originator',
    nameTransliteration: 'Fatir',
    verseCount: 45,
    revelationType: 'meccan',
    order: 43,
  },
  {
    number: 36,
    nameArabic: 'يس',
    nameEnglish: 'Ya-Sin',
    nameTransliteration: 'Ya-Sin',
    verseCount: 83,
    revelationType: 'meccan',
    order: 41,
  },
  {
    number: 37,
    nameArabic: 'الصافات',
    nameEnglish: 'Those Ranged in Ranks',
    nameTransliteration: 'As-Saffat',
    verseCount: 182,
    revelationType: 'meccan',
    order: 56,
  },
  {
    number: 38,
    nameArabic: 'ص',
    nameEnglish: 'The Letter Sad',
    nameTransliteration: 'Sad',
    verseCount: 88,
    revelationType: 'meccan',
    order: 38,
  },
  {
    number: 39,
    nameArabic: 'الزمر',
    nameEnglish: 'The Troops',
    nameTransliteration: 'Az-Zumar',
    verseCount: 75,
    revelationType: 'meccan',
    order: 59,
  },
  {
    number: 40,
    nameArabic: 'غافر',
    nameEnglish: 'The Forgiver',
    nameTransliteration: 'Ghafir',
    verseCount: 85,
    revelationType: 'meccan',
    order: 60,
  },
  {
    number: 41,
    nameArabic: 'فصلت',
    nameEnglish: 'Explained in Detail',
    nameTransliteration: 'Fussilat',
    verseCount: 54,
    revelationType: 'meccan',
    order: 61,
  },
  {
    number: 42,
    nameArabic: 'الشورى',
    nameEnglish: 'The Consultation',
    nameTransliteration: 'Ash-Shura',
    verseCount: 53,
    revelationType: 'meccan',
    order: 62,
  },
  {
    number: 43,
    nameArabic: 'الزخرف',
    nameEnglish: 'The Ornaments of Gold',
    nameTransliteration: 'Az-Zukhruf',
    verseCount: 89,
    revelationType: 'meccan',
    order: 63,
  },
  {
    number: 44,
    nameArabic: 'الدخان',
    nameEnglish: 'The Smoke',
    nameTransliteration: 'Ad-Dukhan',
    verseCount: 59,
    revelationType: 'meccan',
    order: 64,
  },
  {
    number: 45,
    nameArabic: 'الجاثية',
    nameEnglish: 'The Crouching',
    nameTransliteration: 'Al-Jathiyah',
    verseCount: 37,
    revelationType: 'meccan',
    order: 65,
  },
  {
    number: 46,
    nameArabic: 'الأحقاف',
    nameEnglish: 'The Wind-Curved Sandhills',
    nameTransliteration: 'Al-Ahqaf',
    verseCount: 35,
    revelationType: 'meccan',
    order: 66,
  },
  {
    number: 47,
    nameArabic: 'محمد',
    nameEnglish: 'Muhammad',
    nameTransliteration: 'Muhammad',
    verseCount: 38,
    revelationType: 'medinan',
    order: 95,
  },
  {
    number: 48,
    nameArabic: 'الفتح',
    nameEnglish: 'The Victory',
    nameTransliteration: 'Al-Fath',
    verseCount: 29,
    revelationType: 'medinan',
    order: 111,
  },
  {
    number: 49,
    nameArabic: 'الحجرات',
    nameEnglish: 'The Rooms',
    nameTransliteration: 'Al-Hujurat',
    verseCount: 18,
    revelationType: 'medinan',
    order: 106,
  },
  {
    number: 50,
    nameArabic: 'ق',
    nameEnglish: 'The Letter Qaf',
    nameTransliteration: 'Qaf',
    verseCount: 45,
    revelationType: 'meccan',
    order: 34,
  },
  {
    number: 51,
    nameArabic: 'الذاريات',
    nameEnglish: 'The Winnowing Winds',
    nameTransliteration: 'Adh-Dhariyat',
    verseCount: 60,
    revelationType: 'meccan',
    order: 67,
  },
  {
    number: 52,
    nameArabic: 'الطور',
    nameEnglish: 'The Mount',
    nameTransliteration: 'At-Tur',
    verseCount: 49,
    revelationType: 'meccan',
    order: 76,
  },
  {
    number: 53,
    nameArabic: 'النجم',
    nameEnglish: 'The Star',
    nameTransliteration: 'An-Najm',
    verseCount: 62,
    revelationType: 'meccan',
    order: 23,
  },
  {
    number: 54,
    nameArabic: 'القمر',
    nameEnglish: 'The Moon',
    nameTransliteration: 'Al-Qamar',
    verseCount: 55,
    revelationType: 'meccan',
    order: 37,
  },
  {
    number: 55,
    nameArabic: 'الرحمن',
    nameEnglish: 'The Beneficent',
    nameTransliteration: 'Ar-Rahman',
    verseCount: 78,
    revelationType: 'medinan',
    order: 97,
  },
  {
    number: 56,
    nameArabic: 'الواقعة',
    nameEnglish: 'The Inevitable',
    nameTransliteration: "Al-Waqi'ah",
    verseCount: 96,
    revelationType: 'medinan',
    order: 33,
  },
  {
    number: 57,
    nameArabic: 'الحديد',
    nameEnglish: 'The Iron',
    nameTransliteration: 'Al-Hadid',
    verseCount: 29,
    revelationType: 'medinan',
    order: 94,
  },
  {
    number: 58,
    nameArabic: 'المجادلة',
    nameEnglish: 'The Pleading Woman',
    nameTransliteration: 'Al-Mujadila',
    verseCount: 22,
    revelationType: 'medinan',
    order: 105,
  },
  {
    number: 59,
    nameArabic: 'الحشر',
    nameEnglish: 'The Exile',
    nameTransliteration: 'Al-Hashr',
    verseCount: 24,
    revelationType: 'medinan',
    order: 101,
  },
  {
    number: 60,
    nameArabic: 'الممتحنة',
    nameEnglish: 'She That is to be Examined',
    nameTransliteration: 'Al-Mumtahanah',
    verseCount: 13,
    revelationType: 'medinan',
    order: 91,
  },
  {
    number: 61,
    nameArabic: 'الصف',
    nameEnglish: 'The Ranks',
    nameTransliteration: 'As-Saff',
    verseCount: 14,
    revelationType: 'medinan',
    order: 109,
  },
  {
    number: 62,
    nameArabic: 'الجمعة',
    nameEnglish: 'The Congregation',
    nameTransliteration: "Al-Jumu'ah",
    verseCount: 11,
    revelationType: 'medinan',
    order: 110,
  },
  {
    number: 63,
    nameArabic: 'المنافقون',
    nameEnglish: 'The Hypocrites',
    nameTransliteration: 'Al-Munafiqun',
    verseCount: 11,
    revelationType: 'medinan',
    order: 104,
  },
  {
    number: 64,
    nameArabic: 'التغابن',
    nameEnglish: 'The Mutual Disillusion',
    nameTransliteration: 'At-Taghabun',
    verseCount: 18,
    revelationType: 'medinan',
    order: 108,
  },
  {
    number: 65,
    nameArabic: 'الطلاق',
    nameEnglish: 'The Divorce',
    nameTransliteration: 'At-Talaq',
    verseCount: 12,
    revelationType: 'medinan',
    order: 99,
  },
  {
    number: 66,
    nameArabic: 'التحريم',
    nameEnglish: 'The Prohibition',
    nameTransliteration: 'At-Tahrim',
    verseCount: 12,
    revelationType: 'medinan',
    order: 107,
  },
  {
    number: 67,
    nameArabic: 'الملك',
    nameEnglish: 'The Sovereignty',
    nameTransliteration: 'Al-Mulk',
    verseCount: 30,
    revelationType: 'meccan',
    order: 77,
  },
  {
    number: 68,
    nameArabic: 'القلم',
    nameEnglish: 'The Pen',
    nameTransliteration: 'Al-Qalam',
    verseCount: 52,
    revelationType: 'meccan',
    order: 2,
  },
  {
    number: 69,
    nameArabic: 'الحاقة',
    nameEnglish: 'The Reality',
    nameTransliteration: 'Al-Haqqah',
    verseCount: 52,
    revelationType: 'meccan',
    order: 18,
  },
  {
    number: 70,
    nameArabic: 'المعارج',
    nameEnglish: 'The Ascending Stairways',
    nameTransliteration: "Al-Ma'arij",
    verseCount: 44,
    revelationType: 'meccan',
    order: 79,
  },
  {
    number: 71,
    nameArabic: 'نوح',
    nameEnglish: 'Noah',
    nameTransliteration: 'Nuh',
    verseCount: 28,
    revelationType: 'meccan',
    order: 71,
  },
  {
    number: 72,
    nameArabic: 'الجن',
    nameEnglish: 'The Jinn',
    nameTransliteration: 'Al-Jinn',
    verseCount: 28,
    revelationType: 'meccan',
    order: 40,
  },
  {
    number: 73,
    nameArabic: 'المزمل',
    nameEnglish: 'The Enshrouded One',
    nameTransliteration: 'Al-Muzzammil',
    verseCount: 20,
    revelationType: 'meccan',
    order: 3,
  },
  {
    number: 74,
    nameArabic: 'المدثر',
    nameEnglish: 'The Cloaked One',
    nameTransliteration: 'Al-Muddaththir',
    verseCount: 56,
    revelationType: 'meccan',
    order: 4,
  },
  {
    number: 75,
    nameArabic: 'القيامة',
    nameEnglish: 'The Resurrection',
    nameTransliteration: 'Al-Qiyamah',
    verseCount: 40,
    revelationType: 'meccan',
    order: 31,
  },
  {
    number: 76,
    nameArabic: 'الانسان',
    nameEnglish: 'The Human',
    nameTransliteration: 'Al-Insan',
    verseCount: 31,
    revelationType: 'meccan',
    order: 98,
  },
  {
    number: 77,
    nameArabic: 'المرسلات',
    nameEnglish: 'The Emissaries',
    nameTransliteration: 'Al-Mursalat',
    verseCount: 50,
    revelationType: 'meccan',
    order: 80,
  },
  {
    number: 78,
    nameArabic: 'النبإ',
    nameEnglish: 'The Tidings',
    nameTransliteration: 'An-Naba',
    verseCount: 40,
    revelationType: 'meccan',
    order: 30,
  },
  {
    number: 79,
    nameArabic: 'النازعات',
    nameEnglish: 'Those Who Drag Forth',
    nameTransliteration: "An-Nazi'at",
    verseCount: 46,
    revelationType: 'meccan',
    order: 81,
  },
  {
    number: 80,
    nameArabic: 'عبس',
    nameEnglish: 'He Frowned',
    nameTransliteration: "'Abasa",
    verseCount: 42,
    revelationType: 'meccan',
    order: 24,
  },
  {
    number: 81,
    nameArabic: 'التكوير',
    nameEnglish: 'The Overthrowing',
    nameTransliteration: 'At-Takwir',
    verseCount: 29,
    revelationType: 'meccan',
    order: 7,
  },
  {
    number: 82,
    nameArabic: 'الإنفطار',
    nameEnglish: 'The Cleaving',
    nameTransliteration: 'Al-Infitar',
    verseCount: 19,
    revelationType: 'meccan',
    order: 82,
  },
  {
    number: 83,
    nameArabic: 'المطففين',
    nameEnglish: 'The Defrauding',
    nameTransliteration: 'Al-Mutaffifin',
    verseCount: 36,
    revelationType: 'meccan',
    order: 86,
  },
  {
    number: 84,
    nameArabic: 'الإنشقاق',
    nameEnglish: 'The Sundering',
    nameTransliteration: 'Al-Inshiqaq',
    verseCount: 25,
    revelationType: 'meccan',
    order: 83,
  },
  {
    number: 85,
    nameArabic: 'البروج',
    nameEnglish: 'The Mansions of the Stars',
    nameTransliteration: 'Al-Buruj',
    verseCount: 22,
    revelationType: 'meccan',
    order: 27,
  },
  {
    number: 86,
    nameArabic: 'الطارق',
    nameEnglish: 'The Nightcomer',
    nameTransliteration: 'At-Tariq',
    verseCount: 17,
    revelationType: 'meccan',
    order: 36,
  },
  {
    number: 87,
    nameArabic: 'الأعلى',
    nameEnglish: 'The Most High',
    nameTransliteration: "Al-A'la",
    verseCount: 19,
    revelationType: 'meccan',
    order: 8,
  },
  {
    number: 88,
    nameArabic: 'الغاشية',
    nameEnglish: 'The Overwhelming',
    nameTransliteration: 'Al-Ghashiyah',
    verseCount: 26,
    revelationType: 'meccan',
    order: 68,
  },
  {
    number: 89,
    nameArabic: 'الفجر',
    nameEnglish: 'The Dawn',
    nameTransliteration: 'Al-Fajr',
    verseCount: 30,
    revelationType: 'meccan',
    order: 10,
  },
  {
    number: 90,
    nameArabic: 'البلد',
    nameEnglish: 'The City',
    nameTransliteration: 'Al-Balad',
    verseCount: 20,
    revelationType: 'meccan',
    order: 35,
  },
  {
    number: 91,
    nameArabic: 'الشمس',
    nameEnglish: 'The Sun',
    nameTransliteration: 'Ash-Shams',
    verseCount: 15,
    revelationType: 'meccan',
    order: 26,
  },
  {
    number: 92,
    nameArabic: 'الليل',
    nameEnglish: 'The Night',
    nameTransliteration: 'Al-Layl',
    verseCount: 21,
    revelationType: 'meccan',
    order: 9,
  },
  {
    number: 93,
    nameArabic: 'الضحى',
    nameEnglish: 'The Morning Hours',
    nameTransliteration: 'Ad-Duha',
    verseCount: 11,
    revelationType: 'meccan',
    order: 11,
  },
  {
    number: 94,
    nameArabic: 'الشرح',
    nameEnglish: 'The Relief',
    nameTransliteration: 'Ash-Sharh',
    verseCount: 8,
    revelationType: 'meccan',
    order: 28,
  },
  {
    number: 95,
    nameArabic: 'التين',
    nameEnglish: 'The Fig',
    nameTransliteration: 'At-Tin',
    verseCount: 8,
    revelationType: 'meccan',
    order: 16,
  },
  {
    number: 96,
    nameArabic: 'العلق',
    nameEnglish: 'The Clot',
    nameTransliteration: 'Al-Alaq',
    verseCount: 19,
    revelationType: 'meccan',
    order: 1,
  },
  {
    number: 97,
    nameArabic: 'القدر',
    nameEnglish: 'The Power',
    nameTransliteration: 'Al-Qadr',
    verseCount: 5,
    revelationType: 'meccan',
    order: 25,
  },
  {
    number: 98,
    nameArabic: 'البينة',
    nameEnglish: 'The Clear Proof',
    nameTransliteration: 'Al-Bayyinah',
    verseCount: 8,
    revelationType: 'meccan',
    order: 100,
  },
  {
    number: 99,
    nameArabic: 'الزلزلة',
    nameEnglish: 'The Earthquake',
    nameTransliteration: 'Az-Zalzalah',
    verseCount: 8,
    revelationType: 'medinan',
    order: 93,
  },
  {
    number: 100,
    nameArabic: 'العاديات',
    nameEnglish: 'The Courser',
    nameTransliteration: 'Al-Adiyat',
    verseCount: 11,
    revelationType: 'meccan',
    order: 14,
  },
  {
    number: 101,
    nameArabic: 'القارعة',
    nameEnglish: 'The Calamity',
    nameTransliteration: "Al-Qari'ah",
    verseCount: 11,
    revelationType: 'meccan',
    order: 15,
  },
  {
    number: 102,
    nameArabic: 'التكاثر',
    nameEnglish: 'The Rivalry in World Increase',
    nameTransliteration: 'At-Takathur',
    verseCount: 8,
    revelationType: 'meccan',
    order: 17,
  },
  {
    number: 103,
    nameArabic: 'العصر',
    nameEnglish: 'The Declining Day',
    nameTransliteration: 'Al-Asr',
    verseCount: 3,
    revelationType: 'meccan',
    order: 21,
  },
  {
    number: 104,
    nameArabic: 'الهمزة',
    nameEnglish: 'The Traducer',
    nameTransliteration: 'Al-Humazah',
    verseCount: 9,
    revelationType: 'meccan',
    order: 19,
  },
  {
    number: 105,
    nameArabic: 'الفيل',
    nameEnglish: 'The Elephant',
    nameTransliteration: 'Al-Fil',
    verseCount: 5,
    revelationType: 'meccan',
    order: 20,
  },
  {
    number: 106,
    nameArabic: 'قريش',
    nameEnglish: 'Quraysh',
    nameTransliteration: 'Quraysh',
    verseCount: 4,
    revelationType: 'meccan',
    order: 32,
  },
  {
    number: 107,
    nameArabic: 'الماعون',
    nameEnglish: 'The Small Kindnesses',
    nameTransliteration: "Al-Ma'un",
    verseCount: 7,
    revelationType: 'meccan',
    order: 78,
  },
  {
    number: 108,
    nameArabic: 'الكوثر',
    nameEnglish: 'The Abundance',
    nameTransliteration: 'Al-Kawthar',
    verseCount: 3,
    revelationType: 'meccan',
    order: 22,
  },
  {
    number: 109,
    nameArabic: 'الكافرون',
    nameEnglish: 'The Disbelievers',
    nameTransliteration: 'Al-Kafirun',
    verseCount: 6,
    revelationType: 'meccan',
    order: 6,
  },
  {
    number: 110,
    nameArabic: 'النصر',
    nameEnglish: 'The Divine Support',
    nameTransliteration: 'An-Nasr',
    verseCount: 3,
    revelationType: 'medinan',
    order: 13,
  },
  {
    number: 111,
    nameArabic: 'المسد',
    nameEnglish: 'The Palm Fiber',
    nameTransliteration: 'Al-Masad',
    verseCount: 5,
    revelationType: 'meccan',
    order: 12,
  },
  {
    number: 112,
    nameArabic: 'الإخلاص',
    nameEnglish: 'The Sincerity',
    nameTransliteration: 'Al-Ikhlas',
    verseCount: 4,
    revelationType: 'meccan',
    order: 29,
  },
  {
    number: 113,
    nameArabic: 'الفلق',
    nameEnglish: 'The Daybreak',
    nameTransliteration: 'Al-Falaq',
    verseCount: 5,
    revelationType: 'meccan',
    order: 46,
  },
  {
    number: 114,
    nameArabic: 'الناس',
    nameEnglish: 'Mankind',
    nameTransliteration: 'An-Nas',
    verseCount: 6,
    revelationType: 'meccan',
    order: 114,
  },
];
